# Generated by Django 2.1.5 on 2019-02-26 15:10

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'climatic_zone_ratio_data.json', app_label='autodiag_copro')
    call_command('loaddata', 'altitude_ratio_data.json', app_label='autodiag_copro')
    call_command('loaddata', 'default_params_data.json', app_label='autodiag_copro')
    call_command('loaddata', 'default_yearly_params_data.json', app_label='autodiag_copro')
    call_command('loaddata', 'default_combustible_params_data.json', app_label='autodiag_copro')
    call_command('loaddata', 'default_yearly_combustible_params_data.json', app_label='autodiag_copro')


def unload_fixture(apps, schema_editor):
    climatic_zone_ratio_model = apps.get_model("autodiag_copro", "ClimaticZoneRatio")
    climatic_zone_ratio_model.objects.all().delete()
    altitude_ratio_model = apps.get_model("autodiag_copro", "AltitudeRatio")
    altitude_ratio_model.objects.all().delete()
    default_params_model = apps.get_model("autodiag_copro", "DefaultParams")
    default_params_model.objects.all().delete()
    default_yearly_params_model = apps.get_model("autodiag_copro", "DefaultYearlyParams")
    default_yearly_params_model.objects.all().delete()
    default_combustible_params_model = apps.get_model("autodiag_copro", "DefaultCombustibleParams")
    default_combustible_params_model.objects.all().delete()
    default_yearly_combustible_params_model = apps.get_model("autodiag_copro", "DefaultYearlyCombustibleParams")
    default_yearly_combustible_params_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('autodiag_copro', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
