# Generated by Django 2.1.5 on 2019-03-21 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodiag_copro', '0003_auto_20190310_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copro',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='copro',
            name='climatic_zone',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.PROTECT, to='autodiag_copro.ClimaticZoneRatio', verbose_name='Indice de zone climatique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copro',
            name='ref_dju_correction',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Correction DJU de référence'),
        ),
        migrations.AddField(
            model_name='copro',
            name='with_dju_correction',
            field=models.BooleanField(default=False, verbose_name='Avec correction DJU ?'),
        ),
        migrations.AlterField(
            model_name='combustibleparams',
            name='params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustible_params', to='autodiag_copro.Params', verbose_name='Paramètres'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créateur de la demande'),
        ),
        migrations.AlterField(
            model_name='yearlycombustibleparams',
            name='combustible_params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_combustible_params', to='autodiag_copro.CombustibleParams', verbose_name='Paramètres de combustible'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='copro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_data', to='autodiag_copro.Copro', verbose_name='Copropriété'),
        ),
    ]
