# Generated by Django 2.2 on 2019-04-23 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autodiag_copro', '0007_auto_20190415_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copro',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='copro',
            name='contact_first_name',
        ),
        migrations.RemoveField(
            model_name='copro',
            name='contact_last_name',
        ),
        migrations.RemoveField(
            model_name='copro',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='advisor',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_diagnostic', to=settings.AUTH_USER_MODEL, verbose_name='Dernier Conseiller intervenant sur le diagnostic'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé à la demande'),
        ),
    ]
