# Generated by Django 2.2 on 2019-04-30 09:29

import autodiag_copro.models.yearly_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodiag_copro', '0009_auto_20190429_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlydata',
            name='hot_water_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[autodiag_copro.models.yearly_data.validation_absolute_positive], verbose_name='Volume total - eau chaude'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='hot_water_consumption_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[autodiag_copro.models.yearly_data.validation_absolute_positive], verbose_name='Consommation - eau chaude'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='hot_water_energy_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[autodiag_copro.models.yearly_data.validation_absolute_positive], verbose_name='Énergie - eau chaude'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='water_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[autodiag_copro.models.yearly_data.validation_absolute_positive], verbose_name='Volume total - eau froide'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='water_consumption_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[autodiag_copro.models.yearly_data.validation_absolute_positive], verbose_name='Consommation eau froide'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='dju_correction',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[autodiag_copro.models.yearly_data.validation_absolute_positive], verbose_name='Correction DJU'),
        ),
    ]
