# Generated by Django 2.2 on 2019-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodiag_copro', '0011_auto_20190430_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustibleparams',
            name='combustible',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fioul'), (2, 'Gaz de ville'), (3, 'Gaz propane'), (4, 'Réseau de chaleur'), (5, 'Électricité'), (6, 'Bois')], verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='copro',
            name='build_year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Avant 1948'), (2, 'Entre 1948 et 1977'), (3, 'Entre 1977 et 2005'), (4, 'Après 2005')], verbose_name='Année de construction'),
        ),
        migrations.AlterField(
            model_name='copro',
            name='heating_combustible',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fioul'), (2, 'Gaz de ville'), (3, 'Gaz propane'), (4, 'Réseau de chaleur'), (5, 'Électricité'), (6, 'Bois')], verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='copro',
            name='heating_individualisation_mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Surface'), (2, 'Compteurs de chaleur'), (3, 'Répartiteur de chaleur')], verbose_name="Mode d'individualisation des frais de chauffage"),
        ),
        migrations.AlterField(
            model_name='defaultcombustibleparams',
            name='combustible',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fioul'), (2, 'Gaz de ville'), (3, 'Gaz propane'), (4, 'Réseau de chaleur'), (5, 'Électricité'), (6, 'Bois')], verbose_name='Combustible'),
        ),
    ]
