# Generated by Django 2.1.5 on 2019-02-26 15:10

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'default_combustible_params_data.json', app_label='autodiag_copro')


def unload_fixture(apps, schema_editor):
    default_combustible_params_model = apps.get_model("autodiag_copro", "DefaultCombustibleParams")
    default_combustible_params_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('autodiag_copro', '0012_auto_20190522_0922'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
