# Generated by Django 2.2 on 2019-06-07 14:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodiag_copro', '0013_update_default_combustible_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altituderatio',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Indice'),
        ),
        migrations.AlterField(
            model_name='climaticzoneratio',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Indice'),
        ),
        migrations.AlterField(
            model_name='combustibleparams',
            name='avg_hot_water_energy_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro moy. - Ratio de consommation énergétique - eau chaude'),
        ),
        migrations.AlterField(
            model_name='combustibleparams',
            name='eff_hot_water_energy_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro perf. - Ratio de consommation énergétique - eau chaude'),
        ),
        migrations.AlterField(
            model_name='copro',
            name='heating_individualisation_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Frais d'individualisation"),
        ),
        migrations.AlterField(
            model_name='copro',
            name='heating_maintenance_contract_P2_P3_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant du contrat de maintenance P2 + P3'),
        ),
        migrations.AlterField(
            model_name='copro',
            name='heating_maintenance_contract_P2_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant du contrat de maintenance P2'),
        ),
        migrations.AlterField(
            model_name='copro',
            name='living_area',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surface habitable totale'),
        ),
        migrations.AlterField(
            model_name='copro',
            name='number_of_buildings',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de bâtiments'),
        ),
        migrations.AlterField(
            model_name='copro',
            name='number_of_dwellings',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de logements'),
        ),
        migrations.AlterField(
            model_name='defaultcombustibleparams',
            name='avg_hot_water_energy_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro moy. - Ratio de consommation énergétique - eau chaude'),
        ),
        migrations.AlterField(
            model_name='defaultcombustibleparams',
            name='eff_hot_water_energy_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro perf. - Ratio de consommation énergétique - eau chaude'),
        ),
        migrations.AlterField(
            model_name='defaultparams',
            name='avg_hot_water_conso_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro moy. - Ratio de consommation - eau chaude'),
        ),
        migrations.AlterField(
            model_name='defaultparams',
            name='avg_living_area',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Surface moyenne d'un logement"),
        ),
        migrations.AlterField(
            model_name='defaultparams',
            name='avg_water_conso_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro moy. - Ratio de consommation - eau froide'),
        ),
        migrations.AlterField(
            model_name='defaultparams',
            name='eff_hot_water_conso_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro perf. - Ratio de consommation - eau chaude'),
        ),
        migrations.AlterField(
            model_name='defaultparams',
            name='eff_water_conso_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro perf. - Ratio de consommation - eau froide'),
        ),
        migrations.AlterField(
            model_name='defaultyearlycombustibleparams',
            name='avg_energy_cost_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro moy. - Ratio de coût énergie'),
        ),
        migrations.AlterField(
            model_name='defaultyearlycombustibleparams',
            name='eff_energy_cost_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro perf. - Ratio de coût énergie'),
        ),
        migrations.AlterField(
            model_name='defaultyearlyparams',
            name='water_cost',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix eau froide'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='last_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dernière année évaluée'),
        ),
        migrations.AlterField(
            model_name='params',
            name='avg_hot_water_conso_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro moy. - Ratio de consommation - eau chaude'),
        ),
        migrations.AlterField(
            model_name='params',
            name='avg_living_area',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Surface moyenne d'un logement"),
        ),
        migrations.AlterField(
            model_name='params',
            name='avg_water_conso_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro moy. - Ratio de consommation - eau froide'),
        ),
        migrations.AlterField(
            model_name='params',
            name='eff_hot_water_conso_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro perf. - Ratio de consommation - eau chaude'),
        ),
        migrations.AlterField(
            model_name='params',
            name='eff_water_conso_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro perf. - Ratio de consommation - eau froide'),
        ),
        migrations.AlterField(
            model_name='yearlycombustibleparams',
            name='avg_energy_cost_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro moy. - Ratio de coût énergie'),
        ),
        migrations.AlterField(
            model_name='yearlycombustibleparams',
            name='eff_energy_cost_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Copro perf. - Ratio de coût énergie'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='dju_correction',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Correction DJU'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='energy_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Énergie brute'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='heating_energy_charges',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Énergie - chauffage'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='hot_water_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume total - eau chaude'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='hot_water_consumption_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Consommation - eau chaude'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='hot_water_energy_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Énergie - eau chaude'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='water_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume total - eau froide'),
        ),
        migrations.AlterField(
            model_name='yearlydata',
            name='water_consumption_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Consommation eau froide'),
        ),
        migrations.AlterField(
            model_name='yearlyparams',
            name='water_cost',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix eau froide'),
        ),
    ]
