# -*- coding: utf-8 -*-
from django.conf.urls import url

from fac.views import (
    ActionView,
    ContactAndRgpdConsentView,
    ContactView,
    DidActionView,
    EcorenoverSimulationView,
    FileView,
    FolderModelView,
    FolderView,
    GlobalSearchView,
    IncompleteModelView,
    ListView,
    MemberOfOrganizationView,
    NoteView,
    OrganizationView,
    ProjectView,
    RelationBetweenOrganizationView,
    ReminderView,
    StatusView,
    TagView,
    TypeValorizationView,
)

app_name = "fac"
urlpatterns = [
    url(r"^action/$", ActionView.as_view(), name="action_list"),
    url(r"^action/(?P<pk>[^/.]+)/$", ActionView.as_view(), name="action_detail"),
    url(r"^contact/$", ContactView.as_view(), name="contact_list"),
    url(r"^contact/(?P<pk>[^/.]+)/$", ContactView.as_view(), name="contact_detail"),
    url(
        r"^contact_and_rgpd_consent/$",
        ContactAndRgpdConsentView.as_view(),
        name="contact_and_rgpd_consent_list",
    ),
    url(
        r"^contact_and_rgpd_consent/(?P<pk>[^/.]+)/$",
        ContactAndRgpdConsentView.as_view(),
        name="contact_and_rgpd_consent_detail",
    ),
    url(r"^did-action/(?P<pk>[^/.]+)/$", DidActionView.as_view(), name="did_action"),
    url(
        r"^ecorenover-simulation/$",
        EcorenoverSimulationView.as_view(),
        name="ecorenover_simulation_list",
    ),
    url(
        r"^ecorenover-simulation/(?P<pk>[^/.]+)/$",
        EcorenoverSimulationView.as_view(),
        name="ecorenover_simulation_detail",
    ),
    url(r"^file/$", FileView.as_view(), name="file_list"),
    url(r"^file/(?P<pk>[^/.]+)/$", FileView.as_view(), name="file_detail"),
    url(r"^folder/$", FolderView.as_view(), name="folder_list"),
    url(r"^folder/(?P<pk>[^/.]+)/$", FolderView.as_view(), name="folder_detail"),
    url(r"^folder-model/$", FolderModelView.as_view(), name="folder_model_list"),
    url(
        r"^folder-model/(?P<pk>[^/.]+)/$",
        FolderModelView.as_view(),
        name="folder_model_detail",
    ),
    url(r"^incomplete-model/$", IncompleteModelView.as_view(), name="incomplete_model"),
    url(
        r"^incomplete-model/(?P<pk>[^/.]+)/$",
        IncompleteModelView.as_view(),
        name="incomplete_model",
    ),
    url(r"^global_search/$", GlobalSearchView.as_view(), name="global_search"),
    url(r"^list/$", ListView.as_view(), name="list_list"),
    url(r"^list/(?P<pk>[^/.]+)/$", ListView.as_view(), name="list_detail"),
    url(
        r"^member-of-organization/$",
        MemberOfOrganizationView.as_view(),
        name="member_of_organization_list",
    ),
    url(
        r"^member-of-organization/(?P<pk>[^/.]+)/$",
        MemberOfOrganizationView.as_view(),
        name="member_of_organization_detail",
    ),
    url(r"^note/$", NoteView.as_view(), name="note_list"),
    url(r"^note/(?P<pk>[^/.]+)/$", NoteView.as_view(), name="note_detail"),
    url(r"^organization/$", OrganizationView.as_view(), name="organization_list"),
    url(
        r"^organization/(?P<pk>[^/.]+)/$",
        OrganizationView.as_view(),
        name="organization_detail",
    ),
    url(r"^project/$", ProjectView.as_view(), name="project_list"),
    url(r"^project/(?P<pk>[^/.]+)/$", ProjectView.as_view(), name="project_detail"),
    url(
        r"^relation-between-organizations/$",
        RelationBetweenOrganizationView.as_view(),
        name="relation_between_organization_list",
    ),
    url(
        r"^relation-between-organizations/(?P<pk>[^/.]+)/$",
        RelationBetweenOrganizationView.as_view(),
        name="relation_between_organization_detail",
    ),
    url(r"^reminder/$", ReminderView.as_view(), name="reminder_list"),
    url(r"^reminder/(?P<pk>[^/.]+)/$", ReminderView.as_view(), name="reminder_detail"),
    url(r"^status/$", StatusView.as_view(), name="status_list"),
    url(r"^status/(?P<pk>[^/.]+)/$", StatusView.as_view(), name="status_detail"),
    url(r"^tag/$", TagView.as_view(), name="tag_list"),
    url(r"^tag/(?P<pk>[^/.]+)/$", TagView.as_view(), name="tag_detail"),
    url(
        r"^type-valorization/$",
        TypeValorizationView.as_view(),
        name="type_valorization_list",
    ),
    url(
        r"^type-valorization/(?P<pk>[^/.]+)/$",
        TypeValorizationView.as_view(),
        name="type_valorization_detail",
    ),
]
