# Generated by Django 2.2.17 on 2021-02-22 15:58

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_merge_20201201_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Active allowed sender ?', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('group', models.ForeignKey(blank=True, help_text='Structure concernée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jarvis_allowed_sender', to='accounts.Group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Utilisateurs externes autorisé Jarvis/Chef',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
