# -*- coding: utf-8 -*-

# ## Installed apps ##################################

INSTALLED_APPS = [
    "accounts",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.admin",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django_extensions",
    "mail_templated",
    "tagulous",
    "simple_perms",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "background_task",
    "phonenumber_field",
    "ckeditor_uploader",
    "ckeditor_custom",
    "django.contrib.admindocs",
    "jsoneditor",
    "core",
    "white_labelling",
    "territories",
    "visit_report",
    "autodiag_copro",
    "energies",
    "dialogwatt",
    "pdf_generator",
    "fac",
    "thermix",
    "newsletters",
    "nested_admin",
    "recurrence",
    "messaging",
    "actimmo_map",
    "experiences",
    "listepro",
    "ecorenover",
    "jarvis",
    "cti",
    "custom_forms",
    "custom_exports",
]

# ## /Installed apps ##################################
