# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('sender', models.CharField(default='-', max_length=100, verbose_name='sender')),
                ('level', models.CharField(choices=[('debug', 'debug'), ('info', 'info'), ('warning', 'warning'), ('error', 'error'), ('critical', 'critical')], default='debug', max_length=10, verbose_name='Level')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Debug',
                'verbose_name_plural': 'Debug',
                'ordering': ['-creation_date'],
            },
        ),
    ]
