# Generated by Django 2.1.3 on 2018-11-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteLabelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de domaine concerné par la marque blanche')),
                ('site_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre du site')),
                ('favicon', models.CharField(blank=True, max_length=300, null=True, verbose_name='favicon url')),
                ('header', models.TextField(blank=True, max_length=20000, null=True, verbose_name='En tête')),
                ('footer', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Pied de page')),
                ('css', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Feuille CSS personnalisée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Domaine actif')),
            ],
            options={
                'verbose_name': 'Personnalisation marque blanche',
                'ordering': ['pk'],
            },
        ),
    ]
