# Generated by Django 2.1.3 on 2018-11-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("white_labelling", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="whitelabelling",
            name="autodiag_is_active",
            field=models.BooleanField(
                default=True, verbose_name="Activer Autodiagcopro"
            ),
        ),
        migrations.AddField(
            model_name="whitelabelling",
            name="dialogwatt_is_active",
            field=models.BooleanField(default=True, verbose_name="Activer Dialogwatt"),
        ),
        migrations.AddField(
            model_name="whitelabelling",
            name="home_route",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Route de la homepage",
            ),
        ),
        migrations.AddField(
            model_name="whitelabelling",
            name="usermanagement_is_active",
            field=models.BooleanField(
                default=True, verbose_name="Activer la gestion des utilisateurs"
            ),
        ),
    ]
