# Generated by Django 2.2.3 on 2019-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('white_labelling', '0002_auto_20181130_1429'), ('white_labelling', '0003_auto_20181207_2234'), ('white_labelling', '0004_whitelabelling_is_default'), ('white_labelling', '0005_auto_20181210_1818'), ('white_labelling', '0006_auto_20190319_1738'), ('white_labelling', '0007_auto_20190319_1832'), ('white_labelling', '0008_auto_20190321_1835'), ('white_labelling', '0009_whitelabelling_has_menu'), ('white_labelling', '0010_whitelabelling_has_breadcrumb'), ('white_labelling', '0011_auto_20190910_1438')]

    dependencies = [
        ('white_labelling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='autodiag_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Autodiagcopro'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='dialogwatt_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Dialogwatt'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='usermanagement_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer la gestion des utilisateurs'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='home_route_for_administrator',
            field=models.CharField(blank=True, default='Home', max_length=100, null=True, verbose_name='Route de la homepage - administrateurs'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='home_route_for_advisor',
            field=models.CharField(blank=True, default='Home', max_length=100, null=True, verbose_name='Route de la homepage - conseillers'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='home_route_for_client',
            field=models.CharField(blank=True, default='Home', max_length=100, null=True, verbose_name='Route de la homepage - clients'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='home_route_for_manager',
            field=models.CharField(blank=True, default='Home', max_length=100, null=True, verbose_name='Route de la homepage - managers'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='home_route',
            field=models.CharField(blank=True, default='Home', max_length=100, null=True, verbose_name='Route de la homepage - utilisateur non connectés'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Domaine par défaut'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='visit_report_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer le Compte-Rendu de visites'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='dialogwatt_name',
            field=models.CharField(default='DialogWatt', max_length=100, verbose_name="Nom de l'application DialogWatt"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='visit_report_name',
            field=models.CharField(default='Rapport de visite', max_length=100, verbose_name="Nom de l'application Rapport de visite"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Écorénover'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_name',
            field=models.CharField(default='Écorénover', max_length=100, verbose_name="Nom de l'application Écorénover"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='simulaides_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Simulaides'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='simulaides_name',
            field=models.CharField(default='Simulaides', max_length=100, verbose_name="Nom de l'application Simulaides"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='thermix_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Thermix'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='thermix_name',
            field=models.CharField(default='Thermix', max_length=100, verbose_name="Nom de l'application Thermix"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='autodiag_name',
            field=models.CharField(default='AutodiagCopro', max_length=100, verbose_name="Nom de l'application AutodiagCopro"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='autodiag_baseline',
            field=models.CharField(default='Comparer les performances énergétique de ma copropriété', max_length=100, verbose_name="Baseline de l'application AutodiagCopro"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='dialogwatt_baseline',
            field=models.CharField(default='Prendre rendez-vous avec mon conseiller info-énergie', max_length=100, verbose_name="Baseline de l'application DialogWatt"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_baseline',
            field=models.CharField(default="Construction d'un plan de financement pour mes rénovations", max_length=100, verbose_name="Baseline de l'application Écorénover"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='simulaides_baseline',
            field=models.CharField(default='Simuler les aides mobilisables pour le financement de mes travaux', max_length=100, verbose_name="Baseline de l'application Simulaides"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='thermix_baseline',
            field=models.CharField(default='Comparer les systèmes de production de chauffage', max_length=100, verbose_name="Baseline de l'application Thermix"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='visit_report_baseline',
            field=models.CharField(default='Rapport de visite de logements', max_length=100, verbose_name="Baseline de l'application Rapport de visite"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='has_menu',
            field=models.BooleanField(default=True, verbose_name='Montrer le menu ?'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='has_breadcrumb',
            field=models.BooleanField(default=True, verbose_name="Montrer le fil d'ariane ?"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='fac_baseline',
            field=models.CharField(default='Outil de gestion de contacts', max_length=100, verbose_name="Baseline de l'application Fabrique à Contacts"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='fac_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Fabrique à contacts'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='fac_name',
            field=models.CharField(default='Fabrique à contacts', max_length=100, verbose_name="Nom de l'application Fabrique à contacts"),
        ),
    ]
