# Generated by Django 2.1.3 on 2018-12-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("white_labelling", "0002_auto_20181130_1429")]

    operations = [
        migrations.AddField(
            model_name="whitelabelling",
            name="home_route_for_administrator",
            field=models.CharField(
                blank=True,
                default="Home",
                max_length=100,
                null=True,
                verbose_name="Route de la homepage - administrateurs",
            ),
        ),
        migrations.AddField(
            model_name="whitelabelling",
            name="home_route_for_advisor",
            field=models.CharField(
                blank=True,
                default="Home",
                max_length=100,
                null=True,
                verbose_name="Route de la homepage - conseillers",
            ),
        ),
        migrations.AddField(
            model_name="whitelabelling",
            name="home_route_for_client",
            field=models.CharField(
                blank=True,
                default="Home",
                max_length=100,
                null=True,
                verbose_name="Route de la homepage - clients",
            ),
        ),
        migrations.AddField(
            model_name="whitelabelling",
            name="home_route_for_manager",
            field=models.CharField(
                blank=True,
                default="Home",
                max_length=100,
                null=True,
                verbose_name="Route de la homepage - managers",
            ),
        ),
        migrations.AddField(
            model_name="whitelabelling",
            name="visit_report_is_active",
            field=models.BooleanField(default=True, verbose_name="Activer Dialogwatt"),
        ),
        migrations.AlterField(
            model_name="whitelabelling",
            name="home_route",
            field=models.CharField(
                blank=True,
                default="Home",
                max_length=100,
                null=True,
                verbose_name="Route de la homepage - utilisateur non connectés",
            ),
        ),
    ]
