# Generated by Django 2.2.3 on 2019-09-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0002_auto_20181130_1429_squashed_0011_auto_20190910_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='site_baseline',
            field=models.CharField(blank=True, default='Mes services Espace Info Energie', help_text='HTML autorisé', max_length=200, null=True, verbose_name='Baseline du site'),
        ),
    ]
