# Generated by Django 2.1.3 on 2018-12-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("white_labelling", "0003_auto_20181207_2234")]

    operations = [
        migrations.AddField(
            model_name="whitelabelling",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Domaine par défaut"),
        )
    ]
