# Generated by Django 2.1.4 on 2018-12-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("white_labelling", "0004_whitelabelling_is_default")]

    operations = [
        migrations.AlterField(
            model_name="whitelabelling",
            name="visit_report_is_active",
            field=models.BooleanField(
                default=True, verbose_name="Activer le Compte-Rendu de visites"
            ),
        )
    ]
