# Generated by Django 2.2.6 on 2019-11-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0005_auto_20191118_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='clientselfcreation_is_active',
            field=models.BooleanField(default=True, verbose_name="Activer l'auto créations des utilisateurs clients"),
        ),
    ]
