# Generated by Django 2.1.7 on 2019-03-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0006_auto_20190319_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Écorénover'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_name',
            field=models.CharField(default='Écorénover', max_length=100, verbose_name="Nom de l'application Écorénover"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='simulaides_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Simulaides'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='simulaides_name',
            field=models.CharField(default='Simulaides', max_length=100, verbose_name="Nom de l'application Simulaides"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='thermix_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Thermix'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='thermix_name',
            field=models.CharField(default='Thermix', max_length=100, verbose_name="Nom de l'application Thermix"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='autodiag_name',
            field=models.CharField(default='AutodiagCopro', max_length=100, verbose_name="Nom de l'application AutodiagCopro"),
        ),
    ]
