# Generated by Django 2.1.7 on 2019-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0007_auto_20190319_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='autodiag_baseline',
            field=models.CharField(default='Comparer les performances énergétique de ma copropriété', max_length=100, verbose_name="Baseline de l'application AutodiagCopro"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='dialogwatt_baseline',
            field=models.CharField(default='Prendre rendez-vous avec mon conseiller info-énergie', max_length=100, verbose_name="Baseline de l'application DialogWatt"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_baseline',
            field=models.CharField(default="Construction d'un plan de financement pour mes rénovations", max_length=100, verbose_name="Baseline de l'application Écorénover"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='simulaides_baseline',
            field=models.CharField(default='Simuler les aides mobilisables pour le financement de mes travaux', max_length=100, verbose_name="Baseline de l'application Simulaides"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='thermix_baseline',
            field=models.CharField(default='Comparer les systèmes de production de chauffage', max_length=100, verbose_name="Baseline de l'application Thermix"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='visit_report_baseline',
            field=models.CharField(default='Rapport de visite de logements', max_length=100, verbose_name="Baseline de l'application Rapport de visite"),
        ),
    ]
