# Generated by Django 2.2.7 on 2019-11-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0007_auto_20191128_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelabelling',
            name='cee_simul_baseline',
        ),
        migrations.RemoveField(
            model_name='whitelabelling',
            name='cee_simul_is_active',
        ),
        migrations.RemoveField(
            model_name='whitelabelling',
            name='cee_simul_name',
        ),
    ]
