# Generated by Django 2.2.9 on 2020-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0008_auto_20191128_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='autodiag_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer Autodiagcopro'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='clientselfcreation_is_active',
            field=models.BooleanField(default=False, verbose_name="Activer l'auto créations des utilisateurs clients"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='dialogwatt_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer Dialogwatt'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='newsletters_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer les newsletters'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='simulaides_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer Simulaides'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='visit_report_baseline',
            field=models.CharField(default='Édition de rapport entretion logement', max_length=100, verbose_name="Baseline de l'application Rapport de visite"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='visit_report_name',
            field=models.CharField(default="Préco'IMMO", max_length=100, verbose_name="Nom de l'application Rapport de visite"),
        ),
    ]
