# Generated by Django 2.2.3 on 2019-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0009_whitelabelling_has_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='has_breadcrumb',
            field=models.BooleanField(default=True, verbose_name="Montrer le fil d'ariane ?"),
        ),
    ]
