# Generated by Django 2.2.9 on 2020-02-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0009_auto_20200129_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nom de domaine concerné par la marque blanche'),
        ),
    ]
