# Generated by Django 2.2.3 on 2019-09-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0010_whitelabelling_has_breadcrumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='fac_baseline',
            field=models.CharField(default='Outil de gestion de contacts', max_length=100, verbose_name="Baseline de l'application Fabrique à Contacts"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='fac_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Fabrique à contacts'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='fac_name',
            field=models.CharField(default='Fabrique à contacts', max_length=100, verbose_name="Nom de l'application Fabrique à contacts"),
        ),
    ]
