# Generated by Django 2.2.9 on 2020-02-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0010_auto_20200204_1329'),
        ('white_labelling', '0009_auto_20200129_1658'),
    ]

    operations = [
    ]
