# Generated by Django 2.2.9 on 2020-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0014_whitelabelling_fac_hide_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='fac_statistics_is_active',
            field=models.BooleanField(default=False, verbose_name="Activer l'onglet 'Statistiques' de FAC"),
        ),
    ]
