# Generated by Django 2.2.9 on 2020-02-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0015_whitelabelling_fac_statistics_is_active'),
        ('white_labelling', '0014_auto_20200212_1603'),
    ]

    operations = [
    ]
