# Generated by Django 2.2.10 on 2020-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0016_merge_20200212_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='actimmo_map_baseline',
            field=models.CharField(default="Cartographie de l'avancement actimmo", max_length=100, verbose_name="Cartographie de l'avancement actimmo"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='actimmo_map_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer la cartographie actimmo'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='actimmo_map_name',
            field=models.CharField(default='ActimmoMap', max_length=100, verbose_name="Nom de l'application ActimmoMap"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='actimmo_partners_on_map_is_active',
            field=models.BooleanField(default=False, verbose_name='Montrer les partenaires sur la cartographie actimmo'),
        ),
    ]
