# Generated by Django 2.2.9 on 2020-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0016_merge_20200212_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='therminix_baseline',
            field=models.CharField(default='Proposition de solutions de chauffages', max_length=100, verbose_name="Baseline de l'application Therminix"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='therminix_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer Therminix'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='therminix_name',
            field=models.CharField(default='Therminix', max_length=100, verbose_name="Nom de l'application Therminix"),
        ),
    ]
