# Generated by Django 2.2.11 on 2020-04-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0018_whitelabelling_actimmo_map_remove_margins'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='experiences_baseline',
            field=models.CharField(default='Outil de recueil d\'experiences', max_length=100, verbose_name="Baseline de l'application experiences"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='experiences_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer les experiences'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='experiences_name',
            field=models.CharField(default='Experiences', max_length=100, verbose_name="Nom de l'application experiences"),
        ),
    ]
