# Generated by Django 2.2.10 on 2020-04-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0018_whitelabelling_actimmo_map_remove_margins'),
        ('white_labelling', '0017_add_therminix'),
    ]

    operations = [
    ]
