# Generated by Django 2.2.11 on 2020-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0019_auto_20200416_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='experiences_baseline',
            field=models.CharField(default='Outil de recueil de références', max_length=100, verbose_name="Baseline de l'application références"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='experiences_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer les références'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='experiences_name',
            field=models.CharField(default='Experiences', max_length=100, verbose_name="Nom de l'application références"),
        ),
    ]
