# Generated by Django 2.2.10 on 2020-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0020_auto_20200420_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='visit_report_show_wip',
            field=models.BooleanField(default=True, verbose_name='Afficher le message de travaux'),
        ),
    ]
