# Generated by Django 2.2.10 on 2020-05-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0020_auto_20200420_1820'),
        ('white_labelling', '0019_merge_20200403_1705'),
    ]

    operations = [
    ]
