# Generated by Django 2.2.10 on 2020-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0021_whitelabelling_visit_report_show_wip'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='preco_immo_baseline',
            field=models.CharField(default='Édition de rapport entretien logement', max_length=100, verbose_name="Baseline de l'application Préco'immo"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='preco_immo_name',
            field=models.CharField(default="Préco'IMMO", max_length=100, verbose_name="Nom de l'application Préco'Immo"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='visit_report_baseline',
            field=models.CharField(default='Édition de rapport entretien logement', max_length=100, verbose_name="Baseline de l'application Rapport de visite"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='visit_report_name',
            field=models.CharField(default='Compte rendu de RDV', max_length=100, verbose_name="Nom de l'application Rapport de visite"),
        ),
    ]
