# Generated by Django 2.2.10 on 2020-05-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0021_whitelabelling_visit_report_show_wip'),
        ('white_labelling', '0021_merge_20200505_0810'),
    ]

    operations = [
    ]
