# Generated by Django 2.2.10 on 2020-05-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0022_merge_20200512_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='listepro_baseline',
            field=models.CharField(default='Rechercher des professionnels du bâtiment', max_length=100, verbose_name="Baseline de l'application listepro"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='listepro_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer la listepro'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='listepro_name',
            field=models.CharField(default='Liste pro', max_length=100, verbose_name="Nom de l'application listepro"),
        ),
    ]
