# Generated by Django 2.2.10 on 2020-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0022_merge_20200512_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='newsletters_public_baseline',
            field=models.CharField(default='Newsletters', max_length=100, verbose_name="Baseline de l'application publique newsletters"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='newsletters_public_name',
            field=models.CharField(default='Newsletters', max_length=100, verbose_name="Nom de l'application publique newsletters"),
        ),
    ]
