# Generated by Django 2.2.10 on 2020-06-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0023_auto_20200528_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelabelling',
            old_name='ecorenover_baseline',
            new_name='ecorenover_iframe_baseline',
        ),
        migrations.RenameField(
            model_name='whitelabelling',
            old_name='ecorenover_is_active',
            new_name='ecorenover_iframe_is_active',
        ),
        migrations.RenameField(
            model_name='whitelabelling',
            old_name='ecorenover_name',
            new_name='ecorenover_iframe_name',
        ),
    ]
