# Generated by Django 2.2.10 on 2020-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0023_auto_20200528_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='listepro_baseline',
            field=models.CharField(default='Rechercher des professionnels du bâtiment', max_length=100, verbose_name="Baseline de l'application listepro"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='listepro_name',
            field=models.CharField(default='Liste Pro', max_length=100, verbose_name="Nom de l'application listepro"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='old_thermix_baseline',
            field=models.CharField(default='Comparer les systèmes de production de test', max_length=100, verbose_name="Baseline de l'application Thermix (iframe)"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='thermix_baseline',
            field=models.CharField(default='Comparer les systèmes de production de test', max_length=100, verbose_name="Baseline de l'application Thermix"),
        ),
    ]
