# Generated by Django 2.2.10 on 2020-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0024_auto_20200609_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_baseline',
            field=models.CharField(default="Construction d'un plan de financement pour mes rénovations", max_length=100, verbose_name="Baseline de l'application Écorénover"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer Écorénover'),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_name',
            field=models.CharField(default='Écorénover', max_length=100, verbose_name="Nom de l'application Écorénover"),
        ),
        migrations.AddField(
            model_name='whitelabelling',
            name='ecorenover_save_to_fac',
            field=models.BooleanField(default=False, verbose_name='Activer la sauvegarde de simulations Écorénover dans FAC'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='ecorenover_iframe_baseline',
            field=models.CharField(default="Construction d'un plan de financement pour mes rénovations", max_length=100, verbose_name="Baseline de l'application Écorénover (iFrame)"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='ecorenover_iframe_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer Écorénover (iFrame)'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='ecorenover_iframe_name',
            field=models.CharField(default='Écorénover', max_length=100, verbose_name="Nom de l'application Écorénover (iFrame)"),
        ),
    ]
