# Generated by Django 2.2.10 on 2020-05-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0024_auto_20200528_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='experiences_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer les références'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='listepro_is_active',
            field=models.BooleanField(default=True, verbose_name='Activer la listepro'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='old_thermix_baseline',
            field=models.CharField(default='Comparer les systèmes de production de chauffage', max_length=100, verbose_name="Baseline de l'application Thermix (iframe)"),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='thermix_baseline',
            field=models.CharField(default='Comparer les systèmes de production de chauffage', max_length=100, verbose_name="Baseline de l'application Thermix"),
        ),
    ]
