# Generated by Django 2.2.10 on 2020-06-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0025_auto_20200609_1446'),
        ('white_labelling', '0022_auto_20200525_1845'),
    ]

    operations = [
    ]
