# Generated by Django 2.2.10 on 2020-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0025_auto_20200528_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='experiences_is_active',
            field=models.BooleanField(default=False, verbose_name='Activer les références'),
        ),
    ]
