# Generated by Django 2.2.10 on 2020-08-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0026_auto_20200602_1027'),
        ('white_labelling', '0027_whitelabelling_preco_immo_is_active'),
    ]

    operations = [
    ]
