# Generated by Django 2.2.10 on 2020-09-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0028_whitelabelling_enable_django_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='enable_django_admin',
            field=models.BooleanField(default=False, help_text="Cela nécessite impérativement la création d'un enregistrement DNS api-DOMAIN. Sinon cela pose problème avec let's encrypt.", verbose_name='Accès admin django'),
        ),
    ]
