# Generated by Django 2.2.10 on 2020-09-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0029_whitelabelling_home_route_for_professional'),
        ('white_labelling', '0029_auto_20200909_1159'),
    ]

    operations = [
    ]
