# Generated by Django 2.2.10 on 2020-10-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0029_auto_20200909_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='home_route_for_client',
            field=models.CharField(blank=True, default='DashboardClient', max_length=100, null=True, verbose_name='Route de la homepage - clients'),
        ),
    ]
