# Generated by Django 2.2.10 on 2020-11-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0030_auto_20201013_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='is_neutral_for_newsletters',
            field=models.BooleanField(default=False, verbose_name='Domaine neutre pour les newsletters'),
        ),
    ]
