# Generated by Django 2.2.10 on 2020-11-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0030_merge_20200914_1123'),
        ('white_labelling', '0030_auto_20201013_2311'),
    ]

    operations = [
    ]
