# Generated by Django 2.2.10 on 2020-11-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0032_remove_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='home_route',
            field=models.CharField(blank=True, default='AccountLogin', help_text='La route peut prendre des paramètres sous la forme RouteName:param1=x:param2=y', max_length=100, verbose_name='Route de la homepage - utilisateur non connectés'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='home_route_for_administrator',
            field=models.CharField(blank=True, default='GroupList', help_text='La route peut prendre des paramètres sous la forme RouteName:param1=x:param2=y', max_length=100, verbose_name='Route de la homepage - administrateurs'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='home_route_for_advisor',
            field=models.CharField(blank=True, default='FacContactsList', help_text='La route peut prendre des paramètres sous la forme RouteName:param1=x:param2=y', max_length=100, verbose_name='Route de la homepage - conseillers'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='home_route_for_client',
            field=models.CharField(blank=True, default='DashboardClient', max_length=100, verbose_name='Route de la homepage - clients'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='home_route_for_manager',
            field=models.CharField(blank=True, default='GroupList', help_text='La route peut prendre des paramètres sous la forme RouteName:param1=x:param2=y', max_length=100, verbose_name='Route de la homepage - managers'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='site_baseline',
            field=models.CharField(blank=True, default='Mes services Espace Info Energie', help_text='HTML autorisé', max_length=200, verbose_name='Baseline du site'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='site_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Titre du site'),
        ),
    ]
