# Generated by Django 2.2.10 on 2020-12-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0031_merge_20201123_0942'),
        ('white_labelling', '0033_auto_20201119_1339'),
    ]

    operations = [
    ]
