# Generated by Django 2.2.10 on 2020-12-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0035_remove_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabelling',
            name='home_route_for_professional',
            field=models.CharField(blank=True, default='Home', max_length=100, verbose_name='Route de la homepage - professionnels'),
        ),
    ]
