# Generated by Django 2.2.17 on 2021-01-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20200917_1638'),
        ('white_labelling', '0037_auto_20201201_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelling',
            name='sms_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_labelling', to='messaging.SmsAccount', verbose_name='Compte SMS spécifique'),
        ),
        migrations.AlterField(
            model_name='whitelabelling',
            name='smtp_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_labelling', to='messaging.SmtpAccount', verbose_name='Compte SMTP spécifique'),
        ),
    ]
