# Generated by Django 2.2 on 2019-06-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_cache',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cache pour le numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_mobile_cache',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cache pour le numéro de mobile'),
        ),
    ]
