# Generated by Django 2.2.3 on 2019-09-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial_squashed_0010_gps_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsduplicate',
            options={'verbose_name': 'Doublons de contacts', 'verbose_name_plural': 'Doublons de contacts'},
        ),
        migrations.AlterModelOptions(
            name='filecontact',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='fileorganization',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Liste de contacts', 'verbose_name_plural': 'Listes de contacts'},
        ),
        migrations.AlterModelOptions(
            name='memberoforganization',
            options={'verbose_name': "Membre d'organisations", 'verbose_name_plural': "Membres d'organisations"},
        ),
        migrations.AlterModelOptions(
            name='notecontact',
            options={'verbose_name': 'Note de contact', 'verbose_name_plural': 'Notes de contact'},
        ),
        migrations.AlterModelOptions(
            name='noteorganization',
            options={'verbose_name': 'Note de contact', 'verbose_name_plural': 'Notes de contact'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterField(
            model_name='contactsduplicate',
            name='owning_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_duplicate', to='accounts.Group', verbose_name='Groupe propriétaire'),
        ),
        migrations.AlterField(
            model_name='filecontact',
            name='owning_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_contacts', to='accounts.Group', verbose_name='Groupe propriétaire'),
        ),
        migrations.AlterField(
            model_name='fileorganization',
            name='owning_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_organizations', to='accounts.Group', verbose_name='Groupe propriétaire'),
        ),
        migrations.AlterField(
            model_name='filetag',
            name='owning_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tags', to='accounts.Group', verbose_name='Groupe propriétaire'),
        ),
        migrations.AlterField(
            model_name='globaltag',
            name='owning_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_tags', to='accounts.Group', verbose_name='Groupe propriétaire'),
        ),
        migrations.AlterField(
            model_name='list',
            name='owning_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='accounts.Group', verbose_name='Groupe propriétaire'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owning_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='accounts.Group', verbose_name='Groupe propriétaire'),
        ),
    ]
