# Generated by Django 2.2 on 2019-06-07 09:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_auto_20190605_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fax_cache',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cache pour le numéro de fax'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name='Numéro de fax'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name='Numéro de mobile'),
        ),
    ]
