# Generated by Django 2.2 on 2019-06-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190607_1129'),
        ('fac', '0003_auto_20190607_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsduplicate',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_duplicate', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filecontact',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_contacts', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileimport',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_imports', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileorganization',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_organizations', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetag',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_tags', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globaltag',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='global_tags', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='owning_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
    ]
