# Generated by Django 2.2.3 on 2019-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0008_rgpdconsentforcontacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rgpdconsentforcontacts',
            old_name='allow_to_share_my_information_with_ademe',
            new_name='allow_to_share_my_information_with_partners',
        ),
        migrations.AlterField(
            model_name='rgpdconsentforcontacts',
            name='allow_to_share_my_information_with_partners',
            field=models.BooleanField(default=True, verbose_name='Permettre le partage de mes informations avec nos partenaires à des fins statistiques.'),
        ),
    ]
