# Generated by Django 2.2.3 on 2019-09-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0009_auto_20190726_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address3',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='organization',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='organization',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Code postal'),
        ),
    ]
