# Generated by Django 2.2.3 on 2019-09-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190726_1526'),
        ('fac', '0010_gps_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteorganization',
            name='owning_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
    ]
