# Generated by Django 2.2.3 on 2019-09-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0011_noteorganization_owning_group'),
        ('fac', '0002_auto_20190917_1648'),
    ]

    operations = [
    ]
