# Generated by Django 2.2.3 on 2019-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0012_merge_20190923_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address3',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
        ),
    ]
