# Generated by Django 2.2.3 on 2019-10-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190917_1648'),
        ('fac', '0013_gps_address_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecontact',
            name='owning_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notes_contact', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
    ]
