# Generated by Django 2.2.3 on 2019-10-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190917_1648'),
        ('fac', '0014_notecontact_owning_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberoforganization',
            name='owning_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='member_of_organization', to='accounts.Group', verbose_name='Groupe propriétaire'),
            preserve_default=False,
        ),
    ]
