# Generated by Django 2.2.3 on 2019-10-29 10:24

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0003_auto_20191003_1408'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0018_auto_20191024_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(max_length=15000, verbose_name='Note')),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='Date de rappel')),
                ('reminder_done', models.BooleanField(default=False, verbose_name='Rappel traité')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_contact', to='accounts.Group', verbose_name='Groupe propriétaire')),
                ('reminder_persons', models.ManyToManyField(blank=True, default=None, related_name='reminder_persons_notes', to=settings.AUTH_USER_MODEL, verbose_name='Qui rappeler ?')),
                ('tags', models.ManyToManyField(blank=True, help_text='Liste de tags', related_name='linked_notes', to='fac.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Note de contact',
                'verbose_name_plural': 'Notes de contact',
            },
        ),
        migrations.RemoveField(
            model_name='noteorganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='noteorganization',
            name='owning_group',
        ),
        migrations.RemoveField(
            model_name='noteorganization',
            name='reminder_persons',
        ),
        migrations.RemoveField(
            model_name='noteorganization',
            name='tags',
        ),
        migrations.DeleteModel(
            name='NoteContact',
        ),
        migrations.DeleteModel(
            name='NoteOrganization',
        ),
    ]
