# Generated by Django 2.2.3 on 2019-10-29 14:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0019_auto_20191029_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fax_cache',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cache pour le numéro de fax'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_cache',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cache pour le numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name='Numéro de fax'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name='Numéro de téléphone'),
        ),
    ]
