# Generated by Django 2.2.3 on 2019-11-06 13:55

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20191003_1408"),
        ("fac", "0020_auto_20191029_1511"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationBetweenOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    core.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "relation_name",
                    models.CharField(
                        help_text="ex: la maison mère",
                        max_length=100,
                        verbose_name="Nom de la relation entre les structures",
                    ),
                ),
                (
                    "first_organization",
                    models.ForeignKey(
                        help_text="ex: structure parente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_relations",
                        to="fac.Organization",
                        verbose_name="Sujet de la relation",
                    ),
                ),
                (
                    "owning_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_between_organizations",
                        to="accounts.Group",
                        verbose_name="Groupe propriétaire",
                    ),
                ),
                (
                    "second_organization",
                    models.ForeignKey(
                        help_text="ex: structure fille",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backward_relations",
                        to="fac.Organization",
                        verbose_name="Objet de la relation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation entre structures",
                "verbose_name_plural": "Relations entre structures",
            },
        )
    ]
