# Generated by Django 2.2.3 on 2019-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0022_auto_20191114_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Description'),
        ),
    ]
