# Generated by Django 2.2.6 on 2019-11-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0024_auto_20191121_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontact',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Document URL'),
        ),
        migrations.AddField(
            model_name='fileorganization',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Document URL'),
        ),
    ]
