# Generated by Django 2.2.6 on 2019-11-26 10:04

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fac.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0003_auto_20191003_1408'),
        ('fac', '0025_auto_20191121_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.FileField(upload_to=fac.models.file.directory_path, verbose_name='Document')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Document URL')),
                ('note', models.TextField(max_length=15000, verbose_name='Note')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.Group', verbose_name='Groupe propriétaire')),
                ('tags', models.ManyToManyField(blank=True, help_text='Liste de tags', related_name='linked_files', to='fac.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
