# Generated by Django 2.2.7 on 2019-11-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191003_1408'),
        ('fac', '0026_note_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('owning_group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('owning_group', 'name')},
        ),
    ]
