# Generated by Django 2.2.6 on 2019-11-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0027_auto_20191125_1103'),
        ('fac', '0026_file'),
    ]

    operations = [
    ]
