# Generated by Django 2.2.7 on 2019-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0028_merge_20191127_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type_of_organization",
            field=models.CharField(
                choices=[
                    ("AgenceLocale", "Agence Locale"),
                    ("Association", "Association"),
                    ("AssociationIERA", "Association membre IERA"),
                    ("Bailleur", "Bailleur"),
                    ("Collectivity", "Collectivité"),
                    ("Company", "Entreprise"),
                    ("cooperative", "Coopérative"),
                    ("Culture", "Culture"),
                    ("Education", "Éducation"),
                    ("Media", "Média"),
                    ("Syndicat", "Syndicat"),
                    ("RealEstateAgency", "Agence Immo"),
                    ("Bank", "Banque"),
                    ("Broker", "Courtier"),
                    ("Notary", "Notaire"),
                    ("UNKNOWN", "Non précisée"),
                ],
                default="UNKNOWN",
                max_length=50,
                verbose_name="Type d'organisation",
            ),
        ),
    ]
