# Generated by Django 2.2.7 on 2019-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0031_auto_20191129_1623"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="pinned",
            field=models.BooleanField(default=False, verbose_name="Épinglé"),
        ),
        migrations.AddField(
            model_name="note",
            name="pinned",
            field=models.BooleanField(default=False, verbose_name="Épinglée"),
        ),
    ]
