# Generated by Django 2.2.8 on 2019-12-06 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fac', '0032_auto_20191128_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='fac.Contact'),
        ),
        migrations.AddField(
            model_name='action',
            name='reminder_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='folder',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Durée de la tâche en heure'),
        ),
        migrations.AlterField(
            model_name='action',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='actionmodel',
            name='valorizations',
            field=models.ManyToManyField(blank=True, related_name='action_models', to='fac.Valorization', verbose_name='Valorisations'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='type_valorization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='fac.TypeValorization'),
        ),
        migrations.AlterField(
            model_name='foldermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Ce champs doit être édité manuellement uniquement si vous ne renseignez pas de type de valorization.', related_name='folder_models', to='accounts.Group'),
        ),
        migrations.AlterField(
            model_name='foldermodel',
            name='type_valorizations',
            field=models.ManyToManyField(blank=True, related_name='folder_models', to='fac.TypeValorization'),
        ),
    ]
