# Generated by Django 2.2.8 on 2019-12-04 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fac", "0033_auto_20191206_1028"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="done_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "advisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
