# Generated by Django 2.2.8 on 2019-12-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0034_action_done_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fac.Contact', verbose_name='Contact'),
        ),
    ]
