# Generated by Django 2.2.8 on 2019-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0035_auto_20191209_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
