# Generated by Django 2.2.8 on 2019-12-18 15:13

from django.db import migrations, models

new_choices = [
    ("AgenceImmobiliere", "Agence Immobilière"),
    ("Architecte", "Architecte"),
    ("Association", "Association"),
    ("Assureur", "Assureur"),
    ("BailleurSocial", "Bailleur social"),
    ("Banque", "Banque"),
    ("BureauEtudes", "Bureau d'études"),
    ("CommunautDeCommunes", "Communauté de communes"),
    ("Commune", "Commune"),
    ("Courtier", "Courtier"),
    ("Departement", "Département"),
    ("Diagnostiqueur", "Diagnostiqueur"),
    ("EntrepriseRealisation", "Entreprise de la réalisation"),
    ("Etat", "État"),
    ("Fabricant", "Fabricant"),
    ("MaitreOeuvre", "Maître d'œuvre"),
    ("MaitreOuvrage", "Maître d'ouvrage"),
    ("MarchandDeBien", "Marchand de bien"),
    ("Media", "Média"),
    ("Notaire", "Notaire"),
    ("OperateurEnEtancheitAir", "Opérateur en étanchéité à l'air"),
    ("Programmiste", "Programmiste"),
    ("Region", "Région"),
    ("SyndicatDeCoproprietaire", "Syndicat de copropriétaire"),
    ("SyndicatEnergie", "Syndicat d'énergie"),
    ("SyndicatMixte", "Syndicat Mixte"),
    ("UNKNOWN", "Autre"),
]
old_choices = [
    ("AgenceLocale", "Agence Locale"),
    ("Association", "Association"),
    ("AssociationIERA", "Association membre IERA"),
    ("Bailleur", "Bailleur"),
    ("Collectivity", "Collectivité"),
    ("Company", "Entreprise"),
    ("cooperative", "Coopérative"),
    ("Culture", "Culture"),
    ("Education", "Éducation"),
    ("Media", "Média"),
    ("Syndicat", "Syndicat"),
    ("RealEstateAgency", "Agence Immo"),
    ("Bank", "Banque"),
    ("Broker", "Courtier"),
    ("Notary", "Notaire"),
    ("UNKNOWN", "Non précisée"),
]


def alter_type_organization(apps, schema_editor):
    Organization = apps.get_model("fac", "Organization")
    new_choices_keys = {choice[0] for choice in new_choices}
    for organization in Organization.objects.all():
        if organization.type_of_organization not in new_choices_keys:
            organization.type_of_organization = "UNKNOWN"
            organization.save()


def revert_alter_type_organization(apps, schema_editor):
    Organization = apps.get_model("fac", "Organization")
    old_choices_keys = {choice[0] for choice in old_choices}
    for organization in Organization.objects.all():
        if organization.type_of_organization not in old_choices_keys:
            organization.type_of_organization = "UNKNOWN"
            organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0037_auto_20191216_0955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type_of_organization",
            field=models.CharField(
                choices=new_choices,
                default="UNKNOWN",
                max_length=50,
                verbose_name="Type d'organisation",
            ),
        ),
        migrations.RunPython(alter_type_organization, revert_alter_type_organization),
    ]
