# Generated by Django 2.2.8 on 2019-12-12 14:29

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0038_auto_20191218_1613"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="recurrences",
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
