# Generated by Django 2.2.9 on 2020-01-13 14:32

import core.models
from django.db import migrations, models
import django.utils.timezone

ACTIMMO_PK = 99999


def add_project_field(apps, schema_editor):
    Project = apps.get_model("fac", "Project")
    if not Project.objects.filter(pk=ACTIMMO_PK).exists():
        Project.objects.create(name="Actimmo", pk=ACTIMMO_PK)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_group_website"),
        ("fac", "0040_auto_20200106_1534"),
    ]

    operations = [
        migrations.RemoveField(model_name="foldermodel", name="groups",),
        migrations.RemoveField(model_name="foldermodel", name="type_valorizations",),
        migrations.AddField(
            model_name="foldermodel",
            name="icon",
            field=models.CharField(
                choices=[
                    ("euro-sign", "Euro (€)"),
                    ("home", "Maison (🏠)"),
                    ("file-alt", "Fichier (🗎)"),
                    ("chart-bar", "Statistiques (📈)"),
                ],
                default="file-alt",
                max_length=255,
                verbose_name="Icône de dossier",
            ),
        ),
        migrations.AlterField(
            model_name="foldermodel",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Nom du modèle de dossier"
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    core.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "name",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ce champs doit être édité manuellement uniquement si vous ne renseignez pas de type de valorization.",
                        related_name="group_projects",
                        to="accounts.Group",
                    ),
                ),
                (
                    "type_valorizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="type_valorization_projects",
                        to="fac.TypeValorization",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.RunPython(add_project_field, migrations.RunPython.noop),
        migrations.AddField(
            model_name="foldermodel",
            name="project",
            field=models.ForeignKey(
                default=ACTIMMO_PK,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_models",
                to="fac.Project",
                verbose_name="Projet",
            ),
            preserve_default=False,
        ),
    ]
