# Generated by Django 2.2.9 on 2020-01-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0041_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Dossier', 'verbose_name_plural': 'Dossiers'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicateur', 'verbose_name_plural': 'Indicateurs'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Période', 'verbose_name_plural': 'Périodes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='typevalorization',
            options={'verbose_name': 'Type de valorisation', 'verbose_name_plural': 'Types de valorisation'},
        ),
        migrations.AlterModelOptions(
            name='valorization',
            options={'verbose_name': 'Valorisation', 'verbose_name_plural': 'Valorisations'},
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
