# Generated by Django 2.2.9 on 2020-01-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0042_auto_20200113_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="objective",
            name="nb_statuses",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Nombre de status requis"
            ),
            preserve_default=False,
        ),
    ]
