# Generated by Django 2.2.9 on 2020-01-15 14:44

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group_website'),
        ('fac', '0043_objective_nb_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'verbose_name': 'Objectif', 'verbose_name_plural': 'Objectifs'},
        ),
        migrations.AlterField(
            model_name='action',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Durée de la tâche en heure'),
        ),
        migrations.AlterField(
            model_name='valorization',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant à l'acte ou en €/h"),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fixed_part', models.PositiveIntegerField()),
                ('total_envelope', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_budgets', to='accounts.Group', verbose_name='Groupe propriétaire')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_budgets', to='fac.Period')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_budgets', to='fac.Project', verbose_name='Projet lié')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
    ]
