# Generated by Django 2.2.9 on 2020-01-16 09:19

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_group_website'),
        ('fac', '0044_auto_20200115_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='recurrences',
        ),
        migrations.RemoveField(
            model_name='note',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='reminder_done',
        ),
        migrations.RemoveField(
            model_name='note',
            name='reminder_persons',
        ),
        migrations.AddField(
            model_name='note',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Réalisé'),
        ),
        migrations.AddField(
            model_name='note',
            name='done_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'advisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('object_id_task', models.PositiveIntegerField(blank=True, null=True)),
                ('object_id_contactable', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date de rappel')),
                ('recurrences', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('content_type_contactable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_contactable', to='contenttypes.ContentType')),
                ('content_type_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_task', to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Createur')),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.Group', verbose_name='Groupe propriétaire')),
                ('persons', models.ManyToManyField(blank=True, default=None, related_name='reminder_persons', to=settings.AUTH_USER_MODEL, verbose_name='Qui rappeler ?')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
            },
        ),
    ]
