# Generated by Django 2.2.9 on 2020-01-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0045_auto_20200116_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='type_valorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='fac.TypeValorization'),
        ),
    ]
