# Generated by Django 2.2.9 on 2020-01-22 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0046_auto_20200116_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='referents',
            field=models.ManyToManyField(blank=True, help_text='Liste de référents', related_name='contact_referents', to=settings.AUTH_USER_MODEL, verbose_name='Référents'),
        ),
    ]
