# Generated by Django 2.2.9 on 2020-01-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0047_contact_referents"),
    ]

    operations = [
        migrations.RemoveField(model_name="actionmodel", name="category_default",),
        migrations.RemoveField(model_name="actionmodel", name="category_optionnal",),
        migrations.AddField(
            model_name="actionmodel",
            name="category_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_models",
                to="fac.CategoryModel",
            ),
        ),
        migrations.AddField(
            model_name="actionmodel",
            name="default",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Action présente par défaut"
            ),
        ),
        migrations.AddField(
            model_name="actionmodel",
            name="optional",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Action optionnelle"
            ),
        ),
        migrations.AlterField(
            model_name="actionmodel",
            name="category_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_models",
                to="fac.CategoryModel",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionmodel",
            constraint=models.CheckConstraint(
                check=models.Q(("default", True), ("optional", True), _connector="OR"),
                name="default_or_optional",
            ),
        ),
    ]
