# Generated by Django 2.2.9 on 2020-01-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0048_auto_20200122_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="status_cache",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_cache_folders",
                to="fac.Status",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectives",
                to="fac.Period",
                verbose_name="Période",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="folder_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="fac.FolderModel",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectives",
                to="fac.Status",
            ),
        ),
    ]
