# Generated by Django 2.2.9 on 2020-01-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0049_auto_20200121_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldermodel',
            name='icon',
            field=models.CharField(choices=[('euro-sign', 'Euro (€)'), ('house', 'Maison (🏠)'), ('file-alt', 'Fichier (🗎)'), ('pen-fancy', 'Stylo (🖋)')], default='file-alt', max_length=255, verbose_name='Icône de dossier'),
        ),
    ]
