# Generated by Django 2.2.9 on 2020-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0051_remove_budget_fixed_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                verbose_name="Durée de la tâche en heure",
            ),
        ),
    ]
