# Generated by Django 2.2.9 on 2020-01-29 15:56

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_group_website"),
        ("fac", "0052_auto_20200129_1242"),
    ]

    operations = [
        migrations.RenameModel(old_name="Objective", new_name="ObjectiveStatus",),
        migrations.CreateModel(
            name="ObjectiveAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    core.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "nb_actions",
                    models.PositiveIntegerField(
                        verbose_name="Nombre d'actions requises"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectif_actions",
                        to="accounts.Group",
                    ),
                ),
                (
                    "model_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="fac.ActionModel",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objective_actions",
                        to="fac.Period",
                        verbose_name="Période",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif d'action",
                "verbose_name_plural": "Objectifs d'action",
            },
        ),
    ]
