# Generated by Django 2.2.9 on 2020-02-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0053_auto_20200129_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivestatus',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_statuses', to='fac.Period', verbose_name='Période'),
        ),
    ]
