# Generated by Django 2.2.9 on 2020-02-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0054_auto_20200204_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmodel',
            name='coefficient_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer la répartition des valorisations'),
        ),
    ]
