# Generated by Django 2.2.9 on 2020-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0055_actionmodel_coefficient_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmodel',
            name='contact_required',
            field=models.BooleanField(default=False, verbose_name='Contact associé requis'),
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='file_required',
            field=models.BooleanField(default=False, verbose_name='Pièce jointe requise'),
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='message_required',
            field=models.BooleanField(default=False, verbose_name='Commentaire requis'),
        ),
    ]
