# Generated by Django 2.2.9 on 2020-02-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0056_mandatory_action_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionmodel",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="status",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
        ),
    ]
