# Generated by Django 2.2.9 on 2020-02-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0057_auto_20200205_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermodel',
            name='link_to_contact',
            field=models.BooleanField(default=True, verbose_name='Associer à un contact\xa0?'),
        ),
        migrations.AddField(
            model_name='foldermodel',
            name='link_to_organization',
            field=models.BooleanField(default=True, verbose_name='Associer à une structure\xa0?'),
        ),
    ]
