# Generated by Django 2.2.9 on 2020-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0058_auto_20200211_2147'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'model'), name='unique_model_per_object'),
        ),
    ]
