# Generated by Django 2.2.9 on 2020-02-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fac", "0059_unique_constraint_for_folder_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=50, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
    ]
