# Generated by Django 2.2.9 on 2020-02-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0059_unique_constraint_for_folder_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
