# Generated by Django 2.2.9 on 2020-02-14 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0060_auto_20200214_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Adresse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='referents',
            field=models.ManyToManyField(help_text='Liste de référents', related_name='organization_referents', to=settings.AUTH_USER_MODEL, verbose_name='Réferents'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(help_text='Liste de tags', related_name='organizations', to='fac.Tag', verbose_name='Tags'),
        ),
    ]
