# Generated by Django 2.2.9 on 2020-02-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0060_remove_tag_slug'),
        ('fac', '0061_auto_20200214_1557'),
    ]

    operations = [
    ]
