# Generated by Django 2.2.10 on 2020-02-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0064_auto_20200218_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='memberoforganization',
            options={'ordering': ['contact__last_name'], 'verbose_name': "Membre d'organisations", 'verbose_name_plural': "Membres d'organisations"},
        ),
    ]
