# Generated by Django 2.2.9 on 2020-02-20 14:14

from django.db import migrations, models


def populate_reminder_done(apps, schema_editor):
    # Ensure ContentType objects exist at this point:
    # see https://stackoverflow.com/a/40428100
    from django.contrib.contenttypes.management import create_contenttypes

    app_config = apps.get_app_config("fac")
    app_config.models_module = app_config.models_module or True
    create_contenttypes(app_config)

    Action = apps.get_model("fac", "Action")
    Note = apps.get_model("fac", "Note")
    Reminder = apps.get_model("fac", "Reminder")
    ContentType = apps.get_model("contenttypes", "ContentType")

    note_content_type = ContentType.objects.get(app_label="fac", model="note")
    action_content_type = ContentType.objects.get(
        app_label="fac", model="action"
    )

    # move note.done in reminder.done
    for note in Note.objects.all():
        reminder = Reminder.objects.filter(
            content_type_task=note_content_type, object_id_task=note.pk
        ).first()
        if reminder:
            reminder.done = note.done
            reminder.save()

    # move action.done in reminder.done
    for action in Action.objects.all():
        reminder = Reminder.objects.filter(
            content_type_task=action_content_type, object_id_task=action.pk
        ).first()
        if reminder:
            reminder.done = action.done
            reminder.save()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("fac", "0065_auto_20200219_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="done",
            field=models.BooleanField(
                default=False, verbose_name="Le rappel est traité"
            ),
        ),
        migrations.RunPython(
            populate_reminder_done, migrations.RunPython.noop
        ),
        migrations.RemoveField(model_name="note", name="done",),
        migrations.RemoveField(model_name="note", name="done_by",),
    ]
