# Generated by Django 2.2.10 on 2020-02-26 16:56

from django.db import migrations, models
import fac.models.folder_model
import helpers.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0067_auto_20200224_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermodel',
            name='icon_marker',
            field=helpers.fields.SVGField(blank=True, help_text="Ne prend en charge que les fichiers au format SVG. Pour une visualisation optimale de votre icône, il faut utiliser <a href='/static/fac/svg/template.svg' download='template.svg'>ce template</a>.\nIl faut également créer l'icône avec des lignes et non des formes pleines.", null=True, upload_to=fac.models.folder_model.directory_path, verbose_name='Icône'),
        ),
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Couleur'),
        ),
    ]
