# Generated by Django 2.2.10 on 2020-03-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0068_auto_20200226_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='status_cache',
        ),
    ]
