# Generated by Django 2.2.10 on 2020-03-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0069_remove_folder_status_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foldermodel',
            options={
                'ordering': ['pk'],
                'verbose_name': 'Modèle de dossier',
                'verbose_name_plural': 'Modèles de dossier',
            },
        ),
    ]
