# Generated by Django 2.2.10 on 2020-03-05 09:39

from django.db import migrations, models


def all_existing_projects_are_actimmo(apps, schema_editor):
    Project = apps.get_model("fac", "Project")
    Project.objects.all().update(is_actimmo=True)


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0070_auto_20200305_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_actimmo',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            all_existing_projects_are_actimmo, migrations.RunPython.noop
        ),
    ]
