# Generated by Django 2.2.10 on 2020-03-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0071_project_is_actimmo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
    ]
