# Generated by Django 2.2.10 on 2020-03-11 17:19

from django.db import migrations, models


def actimmo_requirements(apps, schema_editor):
    Project = apps.get_model("fac", "Project")
    Project.objects.filter(is_actimmo=True).update(
        is_organization_tags_mandatory=True,
        is_organization_address_mandatory=True,
        is_organization_referents_mandatory=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0072_auto_20200313_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_contact_address_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les contacts liés doivent avoir une adresse',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_contact_email_mandatory',
            field=models.BooleanField(
                default=False, verbose_name='Les contacts liés doivent avoir un email',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_contact_first_name_mandatory',
            field=models.BooleanField(
                default=False, verbose_name='Les contacts liés doivent avoir un prénom',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_contact_last_name_mandatory',
            field=models.BooleanField(
                default=False, verbose_name='Les contacts liés doivent avoir un nom',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_contact_mobile_phone_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les contacts liés doivent avoir numéro de téléphone mobile',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_contact_phone_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les contacts liés doivent avoir un numéro de téléphone',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_contact_referents_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les contacts liés doivent avoir au moins un référent',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_contact_tags_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les contacts liés doivent avoir au moins un tag',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_organization_address_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les structures liées doivent avoir une adresse',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_organization_description_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les structures liées doivent avoir une description',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_organization_email_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les structures liées doivent avoir un email',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_organization_phone_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les structures liées doivent avoir un numéro de téléphone',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_organization_reference_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les structures liées doivent avoir une référence',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_organization_referents_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les structures liées doivent avoir au moins un référent',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_organization_tags_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les structures liées doivent avoir au moins un tag',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='is_organization_website_mandatory',
            field=models.BooleanField(
                default=False,
                verbose_name='Les structures liées doivent avoir un site web',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Adresse'
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_actimmo',
            field=models.BooleanField(default=False, verbose_name='Project ACTIMMO ?'),
        ),
        migrations.RunPython(actimmo_requirements, migrations.RunPython.noop),
    ]
