# Generated by Django 2.2.10 on 2020-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0073_auto_20200311_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmodel',
            name='disabled',
            field=models.BooleanField(default=False, help_text="L'interface ne permettra plus de créer d'actions de ce type, mais les actions existantes ne seront pas supprimées.", verbose_name='Désactiver'),
        ),
    ]
