# Generated by Django 2.2.10 on 2020-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0073_auto_20200311_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldermodel',
            name='icon',
            field=models.CharField(default='file-alt', max_length=255, verbose_name='Icône de dossier'),
        ),
    ]
