# Generated by Django 2.2.10 on 2020-04-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0074_actionmodel_disabled'),
        ('fac', '0074_auto_20200427_1424'),
    ]

    operations = [
    ]
