# Generated by Django 2.2.10 on 2020-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0076_auto_20200429_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmodel',
            name='should_generate_default_actions',
            field=models.BooleanField(default=True, verbose_name='Générer des actions par défaut dans les dossiers existants (si `Action présente par défaut` est cochée)'),
        ),
    ]
