# Generated by Django 2.2.10 on 2020-05-22 13:17

import core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200224_1144'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fac', '0077_actionmodel_should_generate_default_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcorenoverSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('saved_inputs', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Données sauvegardées')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecorenover_simulations', to='accounts.Group', verbose_name='Groupe propriétaire')),
            ],
            options={
                'verbose_name': 'Simulation écorenover',
                'verbose_name_plural': 'Simulations écorenover',
                'ordering': ('-updated_at',),
            },
        ),
    ]
