# Generated by Django 2.2.10 on 2020-07-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0078_ecorenoversimulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Liste de tags', related_name='linked_actions', to='fac.Tag', verbose_name='Tags'),
        ),
    ]
