# Generated by Django 2.2.10 on 2020-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0079_action_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberoforganization',
            name='title_in_organization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Titre dans l'organisation"),
        ),
    ]
