# Generated by Django 2.2.10 on 2020-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0080_auto_20200724_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='should_members_of_organization_respect_rules',
            field=models.BooleanField(default=False, verbose_name="Les contacts membres d'une structure liée doivent respecter les règles du projet"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
    ]
