# Generated by Django 2.2.10 on 2020-10-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0082_auto_20201019_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fax_cache',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cache pour le numéro de fax'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone_cache',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cache pour le numéro de mobile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_cache',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cache pour le numéro de téléphone'),
            preserve_default=False,
        ),
    ]
