# Generated by Django 2.2.10 on 2020-11-19 17:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0083_auto_20201027_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='custom_form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
