# Generated by Django 2.2.17 on 2020-11-26 09:13

import django.core.files.storage
from django.db import migrations, models
import fac.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0083_auto_20201027_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(max_length=500, upload_to=fac.models.file.directory_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='imported_file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/media/imported_files'), upload_to='', verbose_name='Fichier à importer'),
        ),
    ]
