# Generated by Django 2.2.10 on 2020-11-19 17:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0084_contact_custom_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
