# Generated by Django 2.2.17 on 2020-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0085_remove_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, verbose_name='Document URL'),
        ),
    ]
