# Generated by Django 2.2.17 on 2020-11-26 22:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0086_auto_20201126_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_display_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name="Champs à afficher dans l'écran des statistiques et l'export"),
        ),
    ]
