# Generated by Django 2.2.17 on 2020-11-24 10:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0086_action_custom_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
