# Generated by Django 2.2.17 on 2020-11-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0088_folder_custom_form_data'),
        ('fac', '0087_auto_20201130_2213'),
    ]

    operations = [
    ]
