# Generated by Django 2.2.17 on 2020-12-04 15:57

from django.db import migrations

            
def remove_null_for_many_models(apps, schema_editor):
    models = {
        "Organization": [
            "description",
            "address",
            "town",
            "zipcode",
            "country",
            "phone_cache",
            "fax_cache",
        ],
    }
    for model in models:
        postgres_migration_prep(apps, schema_editor, model, fields=models[model])
    

def postgres_migration_prep(apps, schema_editor, model, fields):
    Model = apps.get_model("fac", model.lower())

    for field in fields:
        filter_param = {f"{field}__isnull": True}
        update_param = {field: ""}
        Model.objects.filter(**filter_param).update(**update_param)

        
class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0089_merge_20201130_2359'),
    ]

    operations = [
        migrations.RunPython(remove_null_for_many_models, migrations.RunPython.noop),
    ]
