# Generated by Django 2.2.17 on 2020-12-11 11:02

from django.db import migrations, models

def alter_type_organization(apps, schema_editor):
    Organization = apps.get_model("fac", "Organization")
    Organization.objects.filter(type_of_organization="CommunautDeCommunes").update(type_of_organization="EPCI")

def revert_alter_type_organization(apps, schema_editor):
    Organization = apps.get_model("fac", "Organization")
    Organization.objects.filter(type_of_organization="EPCI").update(type_of_organization="CommunautDeCommunes")


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0091_auto_20201204_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type_of_organization',
            field=models.CharField(choices=[('AgenceImmobiliere', 'Agence Immobilière'), ('Architecte', 'Architecte'), ('Association', 'Association'), ('Assureur', 'Assureur'), ('BailleurSocial', 'Bailleur social'), ('Banque', 'Banque'), ('BureauEtudes', "Bureau d'études"), ('ChambreConsulaire', 'Chambre consulaire'), ('CommunautDeCommunes', 'EPCI'),('EPCI', 'EPCI'), ('Commune', 'Commune'), ('Courtier', 'Courtier'), ('Departement', 'Département'), ('Diagnostiqueur', 'Diagnostiqueur'), ('EnseignementFormation', 'Enseignement et formation'), ('Entreprise', 'Entreprise'), ('EntrepriseRealisation', 'Entreprise de la réalisation'), ('Etat', 'État et établissements publics'), ('Fabricant', 'Fabricant'), ('Fondation', 'Fondation'), ('MaitreOeuvre', "Maître d'œuvre"), ('MaitreOuvrage', "Maître d'ouvrage"), ('MarchandDeBien', 'Marchand de bien'), ('Media', 'Média'), ('Notaire', 'Notaire'), ('OperateurEnEtancheitAir', "Opérateur en étanchéité à l'air"), ('PartenaireHabitat', 'Partenaire habitat'), ('Programmiste', 'Programmiste'), ('Region', 'Région'), ('SyndicatDeCoproprietaire', 'Syndicat de copropriétaire'), ('SyndicatEnergie', "Syndicat d'énergie"), ('SyndicatMixte', 'Syndicat Mixte'), ('UNKNOWN', 'Autre')], default='UNKNOWN', max_length=50, verbose_name="Type d'organisation"),
        ),
        migrations.RunPython(alter_type_organization, revert_alter_type_organization),
        migrations.AlterField(
            model_name='organization',
            name='type_of_organization',
            field=models.CharField(choices=[('AgenceImmobiliere', 'Agence Immobilière'), ('Architecte', 'Architecte'), ('Association', 'Association'), ('Assureur', 'Assureur'), ('BailleurSocial', 'Bailleur social'), ('Banque', 'Banque'), ('BureauEtudes', "Bureau d'études"), ('ChambreConsulaire', 'Chambre consulaire'), ('EPCI', 'EPCI'), ('Commune', 'Commune'), ('Courtier', 'Courtier'), ('Departement', 'Département'), ('Diagnostiqueur', 'Diagnostiqueur'), ('EnseignementFormation', 'Enseignement et formation'), ('Entreprise', 'Entreprise'), ('EntrepriseRealisation', 'Entreprise de la réalisation'), ('Etat', 'État et établissements publics'), ('Fabricant', 'Fabricant'), ('Fondation', 'Fondation'), ('MaitreOeuvre', "Maître d'œuvre"), ('MaitreOuvrage', "Maître d'ouvrage"), ('MarchandDeBien', 'Marchand de bien'), ('Media', 'Média'), ('Notaire', 'Notaire'), ('OperateurEnEtancheitAir', "Opérateur en étanchéité à l'air"), ('PartenaireHabitat', 'Partenaire habitat'), ('Programmiste', 'Programmiste'), ('Region', 'Région'), ('SyndicatDeCoproprietaire', 'Syndicat de copropriétaire'), ('SyndicatEnergie', "Syndicat d'énergie"), ('SyndicatMixte', 'Syndicat Mixte'), ('UNKNOWN', 'Autre')], default='UNKNOWN', max_length=50, verbose_name="Type d'organisation"),
        ),
    ]
