# Generated by Django 2.2.17 on 2020-12-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0087_project_custom_display_fields'),
        ('fac', '0092_auto_20201211_1202'),
    ]

    operations = [
    ]
