# Generated by Django 2.2.17 on 2021-01-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0094_auto_20201221_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_entities_have_multiple_folders_of_same_type',
            field=models.BooleanField(default=True, verbose_name='Les entités du orojet peuvent créer plusieurs dossiers avec le même modèle'),
        ),
    ]
