# Generated by Django 2.2.17 on 2021-01-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0095_project_can_entities_have_multiple_folders_of_same_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_model_per_object',
        ),
    ]
