# Generated by Django 2.2.17 on 2021-02-02 00:53

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0017_merge_20201201_1206'),
        ('fac', '0096_auto_20210107_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncompleteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomplete_model', to='accounts.Group', verbose_name='Groupe propriétaire')),
            ],
            options={
                'verbose_name': 'Objet incomplet',
                'verbose_name_plural': 'Objets incomplets',
                'unique_together': {('owning_group', 'content_type', 'object_id')},
            },
        ),
    ]
