# Generated by Django 2.2.17 on 2021-02-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0097_incompletemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom de la liste'),
        ),
    ]
