# Generated by Django 2.2.17 on 2021-02-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0098_auto_20210210_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberoforganization',
            name='use_address_from_organization',
            field=models.BooleanField(default=False, verbose_name="Utiliser l'adresse de la structure"),
        ),
    ]
