# Generated by Django 2.2.17 on 2021-02-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0099_newsletter_consent'),
        ('fac', '0099_auto_20210223_1608'),
    ]

    operations = [
    ]
