# Generated by Django 2.2.17 on 2021-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0100_merge_20210226_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='inseecode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code INSEE'),
        ),
        migrations.AddField(
            model_name='organization',
            name='inseecode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code INSEE'),
        ),
    ]
