# Generated by Django 2.2.10 on 2020-05-27 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='publication_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de début de publication'),
        ),
    ]
