# Generated by Django 2.2.10 on 2020-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20200528_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together={('group_of_newsletters', 'slug')},
        ),
    ]
