# Generated by Django 2.2.17 on 2020-11-26 09:13

from django.db import migrations, models
import newsletters.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20200616_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(max_length=500, upload_to=newsletters.models.image.image_directory_path, verbose_name='Document'),
        ),
    ]
