# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161206_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('domainname', models.CharField(blank=True, help_text="Tous les utilisateurs dont l'email se termine par ce nom de domaine seront compris dans ce groupe.", max_length=50, verbose_name='Nom de domaine')),
                ('perm', models.CharField(choices=[('group', 'Limité au groupe'), ('ro', 'Visible par tous, modifiable uniquement par les membres du groupe'), ('rw', 'Modifiable par tous')], default='group', max_length=10, verbose_name='Default permissions on contacts and groups')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AddField(
            model_name='user',
            name='civility',
            field=models.CharField(blank=True, choices=[('M.', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], max_length=8, null=True, verbose_name='civility'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=300, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active user ?', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=300, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=300, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_group',
            field=models.ForeignKey(blank=True, help_text="Groupe principal. Il doit être défini si l'utilisateur appartient à plusieurs groupes.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_group', to='accounts.Group', verbose_name='Groupe principal'),
        ),
    ]
