# Generated by Django 2.2.9 on 2020-02-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('white_labelling', '0012_whitelabelling_smtp_account'),
        ('accounts', '0005_group_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='white_labelling',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='white_labelling.WhiteLabelling', verbose_name='Marque blanche préférée'),
        ),
    ]
