# Generated by Django 2.1.3 on 2018-11-25 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("accounts", "0005_auto_20181121_1602")]

    operations = [
        migrations.AddField(
            model_name="group",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Active group ?", verbose_name="active"
            ),
        ),
    ]
