# Generated by Django 2.2.9 on 2020-02-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_group_white_labelling'),
        ('accounts', '0006_auto_20200207_1151'),
    ]

    operations = [
    ]
