# Generated by Django 2.1.4 on 2018-12-09 19:15

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0006_auto_20181125_1757")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.user.profile_directory_path,
            ),
        )
    ]
