# Generated by Django 2.2.9 on 2020-02-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_group_pilot_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="coefficient",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                max_digits=4,
                verbose_name="Coefficient de valorisation",
            ),
        ),
    ]
