# Generated by Django 2.1.5 on 2019-01-17 16:19

import accounts.models.group
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("territories", "0001_initial"),
        ("accounts", "0009_auto_20190109_1709"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="presentation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Présentation de la structure"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.group.group_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="territories",
            field=models.ManyToManyField(
                to="territories.Commune", verbose_name="Territoires"
            ),
        ),
    ]
