# Generated by Django 2.2.9 on 2020-02-24 10:44

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200224_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
