# Generated by Django 2.1.5 on 2019-03-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',), 'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
    ]
