# Generated by Django 2.2 on 2019-04-10 13:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190308_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name='Numéro de téléphone'),
        ),
    ]
