# Generated by Django 2.2.10 on 2020-08-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_group_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('professional', 'Professionnel'), ('advisor', 'Conseiller'), ('superadvisor', 'Super conseiller'), ('manager', 'Responsable'), ('administrator', 'Administrateur')], default='client', max_length=20, verbose_name="Profil d'utilisateur"),
        ),
    ]
