# Generated by Django 2.2.10 on 2020-11-19 11:49

from django.db import migrations


def postgres_migration_prep(apps, schema_editor):
    Contact = apps.get_model("accounts", "user")
    fields = ("civility", "first_name", "title", "phone_cache", "profile_pic")

    for field in fields:
        filter_param = {f"{field}__isnull": True}
        update_param = {field: ""}
        Contact.objects.filter(**filter_param).update(**update_param)

    
def downgrade_object(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_group_address'),
    ]

    operations = [
        migrations.RunPython(postgres_migration_prep, migrations.RunPython.noop),
    ]
