# Generated by Django 2.2.10 on 2020-11-19 11:56

import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='civility',
            field=models.CharField(blank=True, choices=[('M.', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], default='', max_length=8, verbose_name='civility'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_cache',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cache pour le numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to=accounts.models.user.profile_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Titre ou fonction'),
        ),
    ]
