# Generated by Django 2.2 on 2019-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190527_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgpdconsent',
            name='allow_to_share_my_information_with_ademe',
            field=models.BooleanField(default=True, verbose_name="Permettre le partage de mes informations avec l'ademe à des fins statistiques."),
        ),
    ]
