# Generated by Django 2.2.10 on 2020-12-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200814_1112'),
        ('accounts', '0016_auto_20201119_1256'),
    ]

    operations = [
    ]
