# Generated by Django 2.2.17 on 2021-03-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20201201_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ademe_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ADEME_ID for SARE'),
        ),
    ]
