# Generated by Django 2.2 on 2019-06-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190607_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('advisor', 'Conseiller'), ('manager', 'Responsable'), ('administrator', 'Administrateur')], default='client', max_length=20, verbose_name="Profil d'utilisateur"),
        ),
    ]
