# Generated by Django 2.2.11 on 2020-04-22 14:13

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200224_1144'),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Tag actif ?', verbose_name='active')),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group', verbose_name='Groupe propriétaire')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('owning_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExperienceSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du programme')),
                ('contract_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Numéro de contrat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences_sponsor', to='accounts.Group', verbose_name='Groupe propriétaire')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences_sponsors', to='experiences.SponsorTag', verbose_name='Financeur')),
            ],
            options={
                'verbose_name': 'Experience et sponsor',
                'verbose_name_plural': 'Experiences et sponsors',
            },
        ),
    ]
