# Generated by Django 2.2.11 on 2020-04-23 09:07

from django.db import migrations, models
import experiences.models.experience


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_auto_20200422_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=experiences.models.experience.experience_directory_path, verbose_name='Illustration 1'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=experiences.models.experience.experience_directory_path, verbose_name='Illustration 2'),
        ),
    ]
