# Generated by Django 2.2.11 on 2020-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_auto_20200423_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='internal_reference',
            field=models.CharField(default='-', max_length=150, verbose_name='Référence interne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='jobs',
            field=models.ManyToManyField(related_name='experience_jobs', to='experiences.JobTag', verbose_name='Métiers'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='publics',
            field=models.ManyToManyField(related_name='experience_publics', to='experiences.PublicTag', verbose_name='Publics'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.TextField(default='-', verbose_name='Rôle de la structure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.ManyToManyField(related_name='experience_years', to='experiences.YearTag', verbose_name='Années'),
        ),
        migrations.AlterField(
            model_name='experiencesponsor',
            name='contract_number',
            field=models.CharField(default='-', max_length=150, verbose_name='Numéro de contrat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencesponsor',
            name='title',
            field=models.CharField(default='-', max_length=150, verbose_name='Nom du programme'),
            preserve_default=False,
        ),
    ]
