# Generated by Django 2.2.11 on 2020-05-12 10:33

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200224_1144'),
        ('experiences', '0005_auto_20200429_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('starting_a_project', models.TextField(blank=True, null=True, verbose_name='Lancer un projet')),
                ('usefull_docs', models.TextField(blank=True, null=True, verbose_name='Documents utiles')),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences_explanation', to='accounts.Group', verbose_name='Groupe propriétaire')),
            ],
            options={
                'verbose_name': 'Explications',
                'verbose_name_plural': 'Explications',
            },
        ),
        migrations.AddConstraint(
            model_name='explanation',
            constraint=models.UniqueConstraint(fields=('owning_group',), name='one_explanation_by_group'),
        ),
    ]
