# Generated by Django 2.2.10 on 2020-05-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_auto_20200512_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_showcase',
            field=models.BooleanField(default=False, help_text='Projet vitrine', verbose_name='projet vitrine'),
        ),
    ]
