# Generated by Django 2.1.5 on 2019-02-02 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Housing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("house", "Maison"),
                            ("condo", "Copropriété"),
                            ("building", "Immeuble"),
                            ("flat", "Appartement"),
                        ],
                        default="house",
                        max_length=20,
                        verbose_name="Type de logement",
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[("tenant", "Locataire"), ("owner", "Propriétaire")],
                        default="owner",
                        max_length=20,
                        verbose_name="Propriété",
                    ),
                ),
                (
                    "area",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Superficie (en m²"
                    ),
                ),
                (
                    "occupants_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'occupants"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Notes")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="housing",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contact",
                    ),
                ),
            ],
            options={"verbose_name": "Housing"},
        )
    ]
