# Generated by Django 2.1.5 on 2019-02-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0002_auto_20190211_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='area',
            field=models.PositiveIntegerField(default=0, verbose_name='Superficie (en m²)'),
        ),
    ]
