# Generated by Django 2.1.5 on 2019-02-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0003_auto_20190221_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='inseecode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Code INSEE'),
        ),
        migrations.AddField(
            model_name='housing',
            name='is_main_address',
            field=models.BooleanField(default=False, verbose_name='Utiliser comme adresse principale'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='postcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Code postal'),
        ),
    ]
