# Generated by Django 2.1.5 on 2019-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0004_auto_20190221_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='housing_type',
            field=models.CharField(choices=[('house', 'Maison'), ('condo', 'Copropriété'), ('building', 'Immeuble'), ('flat', 'Appartement'), ('other', 'Autre')], default='house', max_length=20, verbose_name='Type de logement'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='ownership',
            field=models.CharField(choices=[('tenant', 'Locataire'), ('owner', 'Propriétaire'), ('other', 'Autre')], default='owner', max_length=20, verbose_name='Propriété'),
        ),
    ]
