# Generated by Django 2.1.5 on 2019-02-28 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0006_auto_20190228_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_report.Scenario', verbose_name='Scénario'),
        ),
        migrations.AlterField(
            model_name='financing',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_report.Scenario', verbose_name='Scénario'),
        ),
        migrations.AlterField(
            model_name='scenariosummary',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_report.Scenario', verbose_name='Scénario'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'advisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to=settings.AUTH_USER_MODEL, verbose_name='Conseiller'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='consumption_information_source',
            field=models.CharField(blank=True, choices=[('bill', 'Facture'), ('dpe', 'DPE'), ('declarative', 'Déclaratif'), ('estimative', 'Estimatif'), ('unavailable', 'Non disponible')], max_length=30, null=True, verbose_name="Source d'information"),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='accounts.Group', verbose_name='Structure signataire'),
        ),
    ]
