# Generated by Django 2.1.5 on 2019-02-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0007_auto_20190228_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkRecommandation',
            new_name='WorkRecommendation',
        ),
    ]
