# Generated by Django 2.2.1 on 2019-05-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0008_auto_20190301_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrecommendation',
            old_name='selected_scenarion_alt',
            new_name='selected_scenario_alt',
        ),
    ]
