# Generated by Django 2.2.3 on 2019-07-11 09:01

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0009_auto_20190515_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='face',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='financialaid',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='financialaid',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='financing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='financing',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='housing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='housing',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='scenario',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='scenario',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='scenariosummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='scenariosummary',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='step',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='step',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='system',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='system',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='workrecommendation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='workrecommendation',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
