# Generated by Django 2.2.3 on 2019-07-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0010_auto_20190711_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='nature',
            field=models.CharField(choices=[('heating-main', 'Production de chauffage'), ('emitter', 'Emetteur'), ('controler', 'Régulation'), ('hot-water', "Production d'eau chaude"), ('heating-extra', "Chauffage d'appoint"), ('ventilation', 'Ventilation'), ('photovoltaic', 'Photovoltaïque')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='consumption_hot_water',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Eau chaude sanitaire'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='dpe',
            field=models.CharField(blank=True, choices=[('a', 'Classe A'), ('b', 'Classe B'), ('c', 'Classe C'), ('d', 'Classe D'), ('e', 'Classe E'), ('-', 'Non connu')], default='-', max_length=2, verbose_name='DPE'),
        ),
        migrations.AlterField(
            model_name='workrecommendation',
            name='category',
            field=models.CharField(choices=[('enveloppe', 'Enveloppe'), ('systems', 'Système'), ('others', 'Autres'), ('eco-gestures', 'Eco gestes')], max_length=25, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='workrecommendation',
            name='nature',
            field=models.CharField(choices=[('roof-insulation', 'Isolation de la toiture'), ('wall-insulation', 'Isolation des murs'), ('floor-insulation', 'Isolation du plancher bas'), ('carpentry-replacement', 'Remplacement des menuiseries'), ('ventilation', 'VMC'), ('heating-production', 'Production de chaleur'), ('heating-emitter', 'Production de chaleur'), ('hot-water-production', "Production d'eau chaude sanitaire"), ('heating-control', 'Régulation du système de chauffage'), ('photovoltaic', 'Installation de panneaux solaires photovoltaïques'), ('eco-gestures', 'Eco gestes'), ('calorifuge', 'Calorifuge'), ('water-tank-insulation', 'water-tank-insulation')], max_length=50, verbose_name='Type'),
        ),
    ]
