# Generated by Django 2.2.3 on 2019-07-17 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_user_color'),
        ('visit_report', '0011_auto_20190713_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitReport',
            new_name='Report',
        ),
    ]
