# Generated by Django 2.2.3 on 2019-07-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0012_auto_20190717_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workrecommendation',
            options={'verbose_name': 'Recommendation de travaux', 'verbose_name_plural': 'Recommendations de travaux'},
        ),
    ]
