# Generated by Django 2.2.3 on 2019-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0014_auto_20190731_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecommendation',
            name='id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
