# Generated by Django 2.2.3 on 2019-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0015_auto_20190802_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='housing_comment',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire sur l'identité du logement"),
        ),
    ]
