# Generated by Django 2.2.3 on 2019-08-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0017_update_scenario_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='year',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Année de construction'),
        ),
    ]
