# Generated by Django 2.2.3 on 2019-08-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0018_housing_year'),
    ]

    operations = [
        migrations.RenameField('step', 'category', 'milestone'),
        migrations.AddField(
            model_name='step',
            name='category',
            field=models.CharField(blank=True, choices=[('financing', 'Quand demander les aides financières ?'), ('contacts', 'Qui contacter ?')], max_length=25, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='step',
            name='nature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='step',
            name='milestone',
            field=models.CharField(blank=True, choices=[('estimation', 'Réalisation du devis'), ('estimation-signature', 'Signature du devis'), ('work-beginning', 'Début des travaux'), ('work-end', 'Fin des travaux')], max_length=25, null=True, verbose_name='Etape du projet'),
        ),
        migrations.AddField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('info', 'Avec infos supplémentaires'), ('contact', 'Avec coordonnées de contact'), ('field', 'Avec saisie libre')], default='regular', max_length=25, verbose_name='Type'),
        ),
    ]
