# Generated by Django 2.2.3 on 2019-09-04 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0020_auto_20190902_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Date de la visite'),
        ),
    ]
