# Generated by Django 2.2.3 on 2019-09-13 15:14

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0023_auto_20190913_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('selected', models.BooleanField(default=False, verbose_name='Sélectionné')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_report.Report', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': 'Annexe',
            },
        ),
    ]
