# Generated by Django 2.2.3 on 2019-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0024_appendix'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='custom_appendix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Annexe personnalisée'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_custom_appendix_selected',
            field=models.BooleanField(default=False, verbose_name='Annexe personnalisée sélectionné'),
        ),
    ]
