# Generated by Django 2.2.3 on 2019-09-25 13:05

from django.db import migrations, models

def update_contacts_steps(apps, schema_editor):
    Steps = apps.get_model('visit_report', 'Step')
    for step in Steps.objects.all():
        if step.category == 'contacts' and step.milestone == 'estimation':
            step.milestone = 'advises'
        elif step.category == 'contacts' and step.milestone == 'estimation-signature':
            step.milestone = 'estimation'
        step.save()

def reverse_update_contacts_steps(apps, schema_editor):
    Steps = apps.get_model('visit_report', 'Step')
    for step in Steps.objects.all():
        if step.category == 'contacts' and step.milestone == 'estimation':
            step.milestone = 'estimation-signature'
        elif step.category == 'contacts' and step.milestone == 'advises':
            step.milestone = 'estimation'
        step.save()

class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0025_auto_20190916_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='milestone',
            field=models.CharField(blank=True, choices=[('advises', 'Conseils/Programmation'), ('estimation', 'Réalisation du devis'), ('estimation-signature', 'Signature du devis'), ('work-beginning', 'Début des travaux'), ('work-end', 'Fin des travaux')], max_length=25, null=True, verbose_name='Etape du projet'),
        ),
        migrations.RunPython(update_contacts_steps, reverse_update_contacts_steps),
    ]
