# Generated by Django 2.2.3 on 2019-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0026_update_contacts_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='ownership',
            field=models.CharField(choices=[('tenant', 'Locataire'), ('owner', 'Propriétaire occupant'), ('landlord', 'Propriétaire bailleur'), ('other', 'Autre')], default='owner', max_length=20, verbose_name='Propriété'),
        ),
    ]
