# Generated by Django 2.2.3 on 2019-09-25 13:05

from django.db import migrations, models

def remove_incorrect_recommendations_heating_systems(apps, schema_editor):
    Recommendations = apps.get_model('visit_report', 'WorkRecommendation')
    for recommendation in Recommendations.objects.all():
        if recommendation.nature == 'heating-production' and recommendation.name in ['oil-boiler-standard', 'gaz-boiler-standard', 'propane-boiler-standard', 'heat-pump-geothermal-vlte', 'heat-pump-geothermal-lte', 'granulated-wood-stove', 'electric-water-heater','ceti-outside-air','ceti-inside-air', 'ceti-extracted-air']:
            recommendation.name = 'oil-boiler-standard'
        recommendation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0027_auto_20190927_1044'),
    ]

    operations = [
        migrations.RunPython(remove_incorrect_recommendations_heating_systems),
    ]
