# Generated by Django 2.2.3 on 2019-10-03 12:48

from django.db import migrations, models

def select_recommendations_for_primary_scenario(apps, schema_editor):
    Recommendations = apps.get_model('visit_report', 'WorkRecommendation')
    for recommendation in Recommendations.objects.all():
        recommendation.selected_scenario_primary = True
        recommendation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0028_update_heating_systems'),
    ]

    operations = [
        migrations.RenameField('workrecommendation', 'selected_scenario_alt', 'selected_scenario_secondary'),
        migrations.AddField(
            model_name='workrecommendation',
            name='selected_scenario_primary',
            field=models.BooleanField(default=False, verbose_name='Sélectionné dans le scénario principal'),
        ),
        migrations.RunPython(select_recommendations_for_primary_scenario),
    ]
