# Generated by Django 2.2.3 on 2019-09-25 13:05

from django.db import migrations, models

def fix_incorrect_recommendations_heating_systems(apps, schema_editor):
    Recommendations = apps.get_model('visit_report', 'WorkRecommendation')
    for recommendation in Recommendations.objects.all():
        if recommendation.nature == 'heating-production' and recommendation.name == 'oil-boiler-standard':
            recommendation.name = 'oil-boiler-condensing'
        recommendation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0029_make_primary_recommendations_editable'),
    ]

    operations = [
        migrations.RunPython(fix_incorrect_recommendations_heating_systems),
    ]
