# Generated by Django 2.2.3 on 2019-10-03 14:41

from django.db import migrations, models

def init_scenario_labels(apps, schema_editor):
    Scenarios = apps.get_model('visit_report', 'Scenario')
    for scenario in Scenarios.objects.all():
        if scenario.nature == 'primary':
            scenario.label = 'Scénario prioritaire'
        else:
            scenario.label = 'Scénario secondaire'
        scenario.save()

class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0030_fixing_migration_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='label',
            field=models.CharField(blank=False, max_length=50, null=False, default="Scénario", verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='workrecommendation',
            name='selected_scenario_secondary',
            field=models.BooleanField(default=False, verbose_name='Sélectionné dans le scénario secondaire'),
        ),
        migrations.RunPython(init_scenario_labels),
    ]
