# Generated by Django 2.2.3 on 2019-09-25 13:05

from django.db import migrations, models

def update_old_heating_systems_not_removed(apps, schema_editor):
    Recommendations = apps.get_model('visit_report', 'WorkRecommendation')
    for recommendation in Recommendations.objects.all():
        if recommendation.nature == 'heating-production' and recommendation.name in ['condensing-boiler', 'wood-insert', 'solar-heater', 'wood-boiler','air-air-heat-pump', 'geothermal-heat-pump', 'wood-stove']:
            recommendation.name = 'oil-boiler-condensing'
        recommendation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0032_auto_20191007_1023'),
    ]

    operations = [
        migrations.RunPython(update_old_heating_systems_not_removed),
    ]
