# Generated by Django 2.2.3 on 2019-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0033_update_old_heating_systems_not_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='identity_comment',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire sur l'identité du maître d'ouvrage"),
        ),
    ]
