# Generated by Django 2.2.8 on 2019-12-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0034_report_identity_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='consumption_heating_hot_water',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Chauffage et eau chaude groupés'),
        ),
    ]
