# Generated by Django 2.2.9 on 2020-02-21 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0035_auto_20191216_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('user_type', 'advisor'), ('user_type', 'superadvisor'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to=settings.AUTH_USER_MODEL, verbose_name='Conseiller'),
        ),
    ]
