# Generated by Django 2.2.10 on 2020-03-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0037_auto_20200227_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendix',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendix', to='visit_report.Report', verbose_name='Rapport'),
        ),
    ]
