# Generated by Django 2.2.10 on 2020-03-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0038_auto_20200316_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='housing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='visit_report.Housing', verbose_name='Logement associé'),
        ),
    ]
