# Generated by Django 2.2.10 on 2020-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0039_auto_20200318_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='face',
            name='data',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Autres données'),
        ),
    ]
