# Generated by Django 2.2.10 on 2020-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0041_add_anah_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='work_recommendations_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire sur les recommandations de travaux'),
        ),
    ]
