# Generated by Django 2.2.10 on 2020-05-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0042_report_work_recommendations_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='financing',
            name='custom_label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Label personnalisé'),
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='custom_label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Label personnalisé'),
        ),
        migrations.AddField(
            model_name='report',
            name='financing_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire sur le financement du projet'),
        ),
    ]
