# Generated by Django 2.2.10 on 2020-05-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0043_auto_20200518_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'verbose_name': 'Logement'},
        ),
    ]
