# Generated by Django 2.2.10 on 2020-06-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('visit_report', '0044_auto_20200527_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='contact_or_organization_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='report',
            name='housing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='visit_report.Housing', verbose_name='Logement associé'),
        ),
    ]
