# Generated by Django 2.2.10 on 2020-06-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0045_auto_20200611_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_custom_summary_selected',
            field=models.BooleanField(default=False, verbose_name='Résumé personnalisé sélectionné'),
        ),
    ]
