# Generated by Django 2.2.10 on 2020-08-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0046_scenario_is_custom_summary_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='custom_appendix',
            field=models.TextField(blank=True, null=True, verbose_name='Annexe personnalisée'),
        ),
    ]
