# Generated by Django 2.2.10 on 2020-10-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0047_auto_20200831_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='address_more',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Complément d'adresse"),
        ),
    ]
