# Generated by Django 2.2.10 on 2020-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_report', '0048_housing_address_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='custom_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé personnalisé'),
        ),
    ]
