# Generated by Django 2.2.10 on 2020-06-02 13:29

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.CharField(choices=[('icon-collectif', 'Icône petit collectif'), ('icon-copro', 'Icône copropriété'), ('icon-maison', 'Icône Maison'), ('icon-tertiaire', 'Icône tertiaire'), ('icon-help', 'Icône par defaut')], default='icon-help', help_text='', max_length=32, verbose_name='Icônes'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(help_text='', max_length=32, verbose_name='Activités'),
        ),
        migrations.AlterField(
            model_name='calculationmethod',
            name='name',
            field=models.CharField(help_text='', max_length=128, verbose_name='Méthodes de calcul'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(help_text='', max_length=32, verbose_name='Métiers'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(help_text='', max_length=32, verbose_name='Mot clé'),
        ),
        migrations.AlterField(
            model_name='keywordcategory',
            name='name',
            field=models.CharField(help_text='', max_length=32, verbose_name='Catégorie de mots clés'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(help_text='', max_length=128, verbose_name='Groupes de missions'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='adress',
            field=models.CharField(help_text='', max_length=256, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='description',
            field=models.TextField(help_text='', max_length=1024, verbose_name='Description longue de votre activité'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(blank=True, help_text='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, help_text='', null=True, verbose_name="Localisation du professionel ou de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='professional',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listepro.ProfessionalImage', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(help_text='', max_length=256, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='personnal_key_words',
            field=models.CharField(blank=True, help_text='', max_length=256, verbose_name='Ajouter vos mots-clés'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='postcode',
            field=models.CharField(help_text='', max_length=6, verbose_name='Code postale'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='short_description',
            field=models.TextField(blank=True, help_text='', max_length=256, null=True, verbose_name='Résumé de votre activité'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='town',
            field=models.CharField(help_text='', max_length=256, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='url',
            field=models.URLField(blank=True, help_text='', verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='professionalimage',
            name='cropped',
            field=models.ImageField(blank=True, help_text='', upload_to='', verbose_name='Image retaillé'),
        ),
        migrations.AlterField(
            model_name='professionalimage',
            name='name',
            field=models.CharField(help_text='', max_length=256, verbose_name="Nom de l'image"),
        ),
        migrations.AlterField(
            model_name='professionalimage',
            name='original',
            field=models.ImageField(blank=True, help_text='', upload_to='', verbose_name='Image originale'),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='airtightness_test_result',
            field=models.CharField(blank=True, help_text='', max_length=512, null=True, verbose_name="Résultat du test d'étanchéité à l'air"),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='completed_mission',
            field=models.CharField(help_text='', max_length=512, verbose_name='Missions réalisées'),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='history',
            field=models.CharField(help_text='', max_length=512, verbose_name='Historique / contexte'),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='label',
            field=models.CharField(blank=True, help_text='', max_length=256, null=True, verbose_name='Label de la réalisation'),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='other_information',
            field=models.CharField(blank=True, help_text='', max_length=512, null=True, verbose_name='Autres informations sur ce projet'),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='pictures',
            field=models.ManyToManyField(help_text='', to='listepro.ProfessionalImage', verbose_name="Image de la réalisation du professionel ou de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='place',
            field=models.CharField(help_text='', max_length=256, verbose_name='Lieu de la réalisation'),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='production_name',
            field=models.CharField(help_text='', max_length=256, verbose_name='Nom de la réalisation'),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='system',
            field=models.CharField(blank=True, help_text='', max_length=512, null=True, verbose_name='Système'),
        ),
        migrations.AlterField(
            model_name='professionalproduction',
            name='thermal_envelope',
            field=models.CharField(blank=True, help_text='', max_length=512, null=True, verbose_name='Enveloppe thermique'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='icon',
            field=models.CharField(choices=[('icon-renovation', 'Icône rénovation'), ('icon-neuve', 'Icône neuve'), ('icon-help', 'Icône par defaut')], default='icon-help', help_text='', max_length=32, verbose_name='Icônes'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(help_text='', max_length=32, verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='usageintegrated',
            name='name',
            field=models.CharField(help_text='', max_length=128, verbose_name='Usages intégrés dans le calcul'),
        ),
    ]
