# Generated by Django 2.2.10 on 2020-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0002_auto_20200602_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='primary_key_words',
            field=models.ManyToManyField(related_name='primary_key_words', to='listepro.KeyWord', verbose_name='Sélectionner vos Mots Clés'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='secondary_key_words',
            field=models.ManyToManyField(related_name='secondary_key_words', to='listepro.KeyWord', verbose_name='Sélectionner vos Mots Clés secondaire'),
        ),
    ]
