# Generated by Django 2.2.10 on 2020-06-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0004_remove_professionalproduction_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='is_valid',
            new_name='pro_is_valid',
        ),
    ]
