# Generated by Django 2.2.10 on 2020-07-02 09:07

from django.db import migrations, models
import listepro.models.professional


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0005_auto_20200629_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=listepro.models.professional.logo_path),
        ),
    ]
