# Generated by Django 2.2.10 on 2020-07-03 07:44

from django.db import migrations, models
import listepro.models.professional_image


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0006_auto_20200702_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalimage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=listepro.models.professional_image.img_prof_path),
        ),
    ]
