# Generated by Django 2.2.10 on 2020-07-03 08:17

from django.db import migrations, models
import listepro.models.professional_image


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0007_professionalimage_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalimage',
            name='logo',
        ),
        migrations.AddField(
            model_name='professionalproduction',
            name='pictures',
            field=models.ManyToManyField(to='listepro.ProfessionalImage', verbose_name="Image de la réalisation du professionel ou de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='professionalimage',
            name='original',
            field=models.ImageField(blank=True, null=True, upload_to=listepro.models.professional_image.img_prof_path),
        ),
    ]
