# Generated by Django 2.2.10 on 2020-07-03 09:43

from django.db import migrations, models
import django.db.models.deletion
import listepro.models.professional_image


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0008_auto_20200703_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalproduction',
            name='pictures',
        ),
        migrations.AddField(
            model_name='professionalimage',
            name='production',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listepro.ProfessionalProduction'),
        ),
        migrations.AlterField(
            model_name='professionalimage',
            name='cropped',
            field=models.ImageField(blank=True, null=True, upload_to=listepro.models.professional_image.img_prof_path),
        ),
        migrations.AlterField(
            model_name='professionalimage',
            name='original',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='Image originale'),
        ),
    ]
