# Generated by Django 2.2.10 on 2020-07-06 08:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0011_auto_20200703_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
