# Generated by Django 2.2.10 on 2020-07-16 12:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0012_auto_20200706_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='geom',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="Localisation du professionel ou de l'entreprise"),
        ),
    ]
