# Generated by Django 2.2.10 on 2020-08-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0014_helper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='order',
        ),
    ]
