# Generated by Django 2.2.10 on 2020-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0015_remove_helper_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='professionalimage',
            name='cropbox',
        ),
        migrations.RemoveField(
            model_name='professionalimage',
            name='original',
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
