# Generated by Django 2.2.10 on 2020-08-20 10:21

from django.db import migrations, models
import listepro.models.professional


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0016_auto_20200814_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='original_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=listepro.models.professional.logo_original_path),
        ),
    ]
