# Generated by Django 2.2.10 on 2020-08-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0017_professional_original_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='comment',
            field=models.TextField(max_length=2000, null=True, verbose_name='Commentaire sur le professionnel'),
        ),
    ]
