# Generated by Django 2.2.17 on 2020-11-26 10:29

from django.db import migrations


def postgres_migration_prep(apps, schema_editor, model, fields):
    Model = apps.get_model("listepro", model.lower())

    for field in fields:
        filter_param = {f"{field}__isnull": True}
        update_param = {field: ""}
        Model.objects.filter(**filter_param).update(**update_param)

            
def remove_null_for_many_models(apps, schema_editor):
    models = {
        "Helper": ["help_text"],
        "SubMission": ["help_text"],
        "ProfessionalImage": ["cropped"],
        "ProfessionalProduction": [
            "label",
            "thermal_envelope",
            "system",
            "airtightness_test_result",
            "other_information"
        ],
        "Professional": ["email", "url", "logo", "original_logo", "comment"],
        "Mission": ["help_text"],
    }
    for model in models:
        postgres_migration_prep(apps, schema_editor, model, fields=models[model])
    

class Migration(migrations.Migration):

    dependencies = [
        ('listepro', '0019_auto_20200824_1049'),
    ]

    operations = [
        migrations.RunPython(remove_null_for_many_models, migrations.RunPython.noop),
    ]
