# Generated by Django 2.2.9 on 2020-01-24 08:39

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_group_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.CharField(max_length=100, verbose_name='Compte')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name='Numéro de téléphone Twilio')),
                ('is_active', models.BooleanField(default=True, help_text='Compte actif ?', verbose_name='active')),
                ('monthly_limit', models.IntegerField(default=1000, verbose_name='Limite mensuelle de sms envoyés')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_twilio_account', to='accounts.Group', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'Compte Twilio',
            },
        ),
        migrations.CreateModel(
            name='SmtpAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Compte actif ?', verbose_name='active')),
                ('smtp_type', models.CharField(choices=[('mailgun', 'Mailgun'), ('smtp', 'SMTP')], default='smtp', max_length=20, verbose_name='Type de serveur mail')),
                ('mailgun_apikey', models.CharField(blank=True, max_length=100, verbose_name="Clef d'API")),
                ('mailgun_monthly_limit', models.IntegerField(default=10000, verbose_name="Limite mensuelle d'envois")),
                ('email_host', models.CharField(blank=True, max_length=100, verbose_name='SMTP serveur')),
                ('email_port', models.IntegerField(default=25, verbose_name='SMTP port')),
                ('email_host_user', models.CharField(blank=True, max_length=100, verbose_name='SMTP utilisateur')),
                ('email_host_password', models.CharField(blank=True, max_length=100, verbose_name='SMTP mot de passe')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='SMTP utiliser TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='SMTP utiliser SSL')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_smtp_account', to='accounts.Group', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'Configuration SMTP/Mailgun',
            },
        ),
    ]
