# Generated by Django 2.2.9 on 2020-02-07 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='smtpaccount',
            managers=[
                ('system_wide', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='name',
            field=models.CharField(default='Configuration SMTP', max_length=100, verbose_name='Nom de la configuration'),
        ),
        migrations.AlterField(
            model_name='smtpaccount',
            name='group',
            field=models.OneToOneField(blank=True, help_text="Si aucune structure n'est sélectionnée, il s'agit d'une configuration globale", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_smtp_account', to='accounts.Group', verbose_name='Structure'),
        ),
    ]
