# Generated by Django 2.2.10 on 2020-03-05 10:34

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200224_1144'),
        ('messaging', '0003_smtpaccount_from_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account_type', models.CharField(choices=[('twilio', 'Twilio'), ('ovh', 'OVH')], default='ovh', max_length=20, verbose_name='Type de serveur mail')),
                ('twilio_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Compte Twilio')),
                ('twilio_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token Twilio')),
                ('ovh_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Compte OVH')),
                ('ovh_login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifiant OVH')),
                ('ovh_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mot de passe OVH')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, verbose_name="Numéro de téléphone d'expédition")),
                ('is_active', models.BooleanField(default=True, help_text='Compte actif ?', verbose_name='active')),
                ('monthly_limit', models.IntegerField(default=1000, verbose_name='Limite mensuelle de sms envoyés')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_sms_account', to='accounts.Group', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'Compte envois de SMS',
            },
        ),
    ]
