# Generated by Django 2.2.10 on 2020-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_smsaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro de téléphone d'expédition"),
        ),
    ]
