# Generated by Django 2.2.10 on 2020-09-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20200310_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsaccount',
            name='ovh_sender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Expéditeur'),
        ),
    ]
