# Generated by Django 2.2.10 on 2020-09-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0080_auto_20200724_1528'),
        ('messaging', '0006_smsaccount_ovh_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacContactForDialogwatt',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fac.contact',),
        ),
        migrations.DeleteModel(
            name='TwilioAccount',
        ),
    ]
