# Generated by Django 2.2.10 on 2020-09-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20200911_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacContactForDialogwatt',
        ),
    ]
