# Generated by Django 2.2.10 on 2020-09-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_delete_faccontactfordialogwatt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsaccount',
            name='account_type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('ovh', 'OVH'), ('mail', 'mail backend for debug')], default='ovh', max_length=20, verbose_name='Type de serveur mail'),
        ),
    ]
