# Generated by Django 2.2.10 on 2020-04-20 07:21
from decimal import Decimal
from django.db import migrations


def set_2019_energy_prices(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")
    YearlyEnergyPrice = apps.get_model("energies", "YearlyEnergyPrice")

    def set_values(
        energy_identifier,
        year=None,
        price=None,
        variation=None,
        ghg_ratio=None,
        price_multi_unit_discount=None,
    ):
        energy = Energy.objects.get(identifier=energy_identifier)
        if year and price:
            YearlyEnergyPrice.objects.update_or_create(
                energy=energy, year=year, defaults={"price": Decimal(price)}
            )
        if variation:
            energy.price_variation = Decimal(variation)
        if ghg_ratio:
            energy.ghg_ratio = Decimal(ghg_ratio)
        if price_multi_unit_discount:
            energy.price_multi_unit_discount = Decimal(price_multi_unit_discount)
        energy.save()

    set_values("oil", 2019, "9.38", "0.0497", "0.324")
    set_values("propane", 2019, "14.92", "0.0381", "0.272")
    set_values("gaz_b1", 2019, "7.36", "0.0271", "0.205")
    set_values("electricity", 2019, "16.01", "0.0174", "0.147")
    set_values("wood", 2019, "4.62", "0.0271", "0.030")
    set_values(
        "shredded_wood", 2019, "3.16", "0.0202", "0.024", price_multi_unit_discount="0.99"
    )
    set_values("bulk_granules", 2019, "6.15", "0.0288", "0.030")
    set_values("bag_granules", 2019, "6.46", "0.0288", "0.030")
    set_values("network", 2019, "3.65", "0.02", "0.140")


class Migration(migrations.Migration):

    dependencies = [
        ("energies", "0002_data_reset_energy_prices"),
    ]

    operations = [
        migrations.RunPython(
            set_2019_energy_prices, reverse_code=migrations.RunPython.noop
        )
    ]
