# Generated by Django 2.2 on 2019-04-30 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0002_auto_20190317_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='yearlyenergyprice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
