# Generated by Django 2.2.10 on 2020-05-10 07:28
from decimal import Decimal
from django.db import migrations


def fix_heating_network(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")
    network = Energy.objects.get(identifier="network")

    network.primary_energy_ratio = Decimal("1")
    network.ghg_ratio = Decimal("0.14")
    network.carbon_tax = False
    network.pci_ratio = None
    network.density_ratio = None
    network.combustible_category = "renewable"
    network.price_variation = Decimal("0.02")
    network.price_multi_unit_discount = Decimal("0.96")
    network.save()

    EnergyVector = apps.get_model("energies", "EnergyVector")
    network_vector = EnergyVector.objects.get(energy=network)
    network_vector.network_vector = "kWh"
    network_vector.pci = Decimal("1")
    network_vector.unit = "kWh"
    network_vector.save()

    ProductionSystem = apps.get_model("energies", "ProductionSystem")
    heating_network = ProductionSystem.objects.get(identifier='heating_network')
    heating_network.is_heating = True
    heating_network.is_hot_water = True
    heating_network.is_individual = False
    heating_network.is_multi_unit = True
    heating_network.is_hydro = True
    heating_network.efficiency_heating = Decimal('1')
    heating_network.efficiency_hot_water = Decimal('1')
    heating_network.enr_ratio_heating = Decimal('0.6')
    heating_network.enr_ratio_hot_water = Decimal('0.6')
    heating_network.investment_individual_heating = None
    heating_network.investment_individual_hot_water = None
    heating_network.maintenance_individual_heating = None
    heating_network.maintenance_individual_hot_water = None
    heating_network.investment_small_multi_unit_heating = Decimal('2000')
    heating_network.investment_small_multi_unit_hot_water = Decimal('2000')
    heating_network.maintenance_small_multi_unit_heating = Decimal('4300')
    heating_network.maintenance_small_multi_unit_hot_water = Decimal('5300')
    heating_network.provisions_small_multi_unit_heating = Decimal('4300')
    heating_network.provisions_small_multi_unit_hot_water = Decimal('5300')
    heating_network.investment_medium_multi_unit_heating = Decimal('4000')
    heating_network.investment_medium_multi_unit_hot_water = Decimal('4000')
    heating_network.maintenance_medium_multi_unit_heating = Decimal('8600')
    heating_network.maintenance_medium_multi_unit_hot_water = Decimal('10100')
    heating_network.provisions_medium_multi_unit_heating = Decimal('8600')
    heating_network.provisions_medium_multi_unit_hot_water = Decimal('10100')
    heating_network.investment_large_multi_unit_heating = Decimal('6000')
    heating_network.investment_large_multi_unit_hot_water = Decimal('6000')
    heating_network.maintenance_large_multi_unit_heating = Decimal('12900')
    heating_network.maintenance_large_multi_unit_hot_water = Decimal('14900')
    heating_network.provisions_large_multi_unit_heating = Decimal('12900')
    heating_network.provisions_large_multi_unit_hot_water = Decimal('14900')
    heating_network.save()


class Migration(migrations.Migration):

    dependencies = [
        ("energies", "0004_auto_20200505_1408"),
    ]

    operations = [
        migrations.RunPython(fix_heating_network, reverse_code=migrations.RunPython.noop),
    ]
