# Generated by Django 2.2 on 2019-05-02 14:42

from django.db import migrations


def add_energy_type(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")
    if not Energy.objects.filter(identifier='network').exists():
        Energy.objects.create(
            identifier="network",
            primary_energy_ratio=1,
            ghg_ratio=0.05,
            carbon_tax=False,
            pci_ratio=None,
            density_ratio=None,
        )


def reverse_add_energy_type(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")
    Energy.objects.filter(identifier="network").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0004_fix_energy_and_yearly_price'),
    ]

    operations = [
        migrations.RunPython(add_energy_type, reverse_code=reverse_add_energy_type),
    ]
