# Generated by Django 2.2.10 on 2020-05-12 10:43
from decimal import Decimal
from django.db import migrations


def load_data(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")
    # EnergyVector = apps.get_model("energies", "EnergyVector")
    ProductionSystem = apps.get_model("energies", "ProductionSystem")

    wood = Energy.objects.get(identifier="wood")
    # wood_logs_stere = EnergyVector.objects.get(identifier="wood_logs_stere")
    ProductionSystem.objects.create(
        identifier="old_log_stove",
        energy=wood,
        is_heating=True,
        is_hot_water=False,
        is_individual=True,
        is_multi_unit=False,
        is_hydro=False,
        efficiency_heating=Decimal("0.5"),
        enr_ratio_heating=Decimal("1"),
    )
    ProductionSystem.objects.create(
        identifier="log_insert",
        energy=wood,
        is_heating=True,
        is_hot_water=False,
        is_individual=True,
        is_multi_unit=False,
        is_hydro=False,
        efficiency_heating=Decimal("0.75"),
        enr_ratio_heating=Decimal("1"),
        investment_individual_heating=3000,
        maintenance_individual_heating=80,
    )
    ProductionSystem.objects.create(
        identifier="old_log_insert",
        energy=wood,
        is_heating=True,
        is_hot_water=False,
        is_individual=True,
        is_multi_unit=False,
        is_hydro=False,
        efficiency_heating=Decimal("0.4"),
        enr_ratio_heating=Decimal("1"),
    )
    ProductionSystem.objects.create(
        identifier="fireplace",
        energy=wood,
        is_heating=True,
        is_hot_water=False,
        is_individual=True,
        is_multi_unit=False,
        is_hydro=False,
        efficiency_heating=Decimal("0.15"),
        enr_ratio_heating=Decimal("1"),
    )

    # Fix log stove efficiency
    ProductionSystem.objects.filter(identifier="log_stove").update(
        efficiency_heating=Decimal("0.75")
    )


def rollback_data(apps, schema_editor):
    ProductionSystem = apps.get_model("energies", "ProductionSystem")
    
    ProductionSystem.objects.filter(identifier="log_stove").update(
        efficiency_heating=Decimal("0.70")
    )
    
    ProductionSystem.objects.filter(
        identifier__in=["old_log_stove", "log_insert", "old_log_insert", "fireplace"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("energies", "0006_new_logs_based_production_systems"),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_code=rollback_data),
    ]
