# Generated by Django 2.2.10 on 2020-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energies", "0005_fix_heating_network_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsystem',
            name='identifier',
            field=models.CharField(choices=[('oil_boiler_standard', 'Chaudière fioul standard'), ('oil_boiler_condensing', 'Chaudière fioul condensation'), ('gaz_boiler_standard', 'Chaudière gaz standard'), ('gaz_boiler_condensing', 'Chaudière gaz condensation'), ('propane_boiler_standard', 'Chaudière propane standard'), ('propane_boiler_condensing', 'Chaudière propane condensation'), ('electric_boiler', 'Chaudière électrique'), ('electric_radiators', 'Radiateurs électriques'), ('heat_pump_air_air', 'PAC air/air'), ('heat_pump_air_water', 'PAC air/eau '), ('heat_pump_geothermal_lte', 'PAC géothermale avec émetteurs basse température'), ('heat_pump_geothermal_vlte', 'PAC géothermale avec émetteurs très basse température'), ('thermodynamic_cmv', 'VMC thermodynamique'), ('log_stove', 'Poêle à bûches récent'), ('old_log_stove', 'Poêle à bûches ancien'), ('log_insert', 'Insert à bûches récent'), ('old_log_insert', 'Insert à bûches ancien'), ('fireplace', 'Cheminée ouverte'), ('granulated_wood_stove', 'Poêle à bois granulés'), ('granulated_wood_boiler', 'Chaudière à bois granulés'), ('log_boiler', 'Chaudière à bûches'), ('shredded_wood_boiler', 'Chaudière à bois déchiqueté'), ('recent_log_boiler_stove', 'Poêle à bûches récent bouilleur'), ('granulated_wood_boiler_stove', 'Poêle à bois granulés bouilleur'), ('electric_water_heater', 'Chauffe-eau électrique'), ('ceti_outside_air', 'CETI sur air extérieur'), ('ceti_inside_air', 'CETI sur air intérieur'), ('ceti_extracted_air', 'CETI sur air extrait'), ('heat_pump_using_waste_heat', 'PAC valorisant une chaleur perdue (eaux grises etc.)'), ('heating_network', 'RCU (Réseau de Chaleur Urbain)'), ('solar_system_combined', 'Système Solaire Combiné'), ('solar_water_heater', 'Chauffe-eau Solaire')], max_length=50, unique=True, verbose_name='Identifiant'),
        ),
    ]
