# Generated by Django 2.2.10 on 2020-08-20 14:37

from django.db import migrations


def fix_granulated_wood_boiler_maintenance_price(apps, schema_editor):
    ProductionSystem = apps.get_model("energies", "ProductionSystem")

    granulated_wood_boiler_stove = ProductionSystem.objects.get(
        identifier="granulated_wood_boiler_stove"
    )

    granulated_wood_boiler_stove.investment_individual_hot_water = 3000
    granulated_wood_boiler_stove.save()


def unfix_granulated_wood_boiler_maintenance_price(apps, schema_editor):
    ProductionSystem = apps.get_model("energies", "ProductionSystem")

    granulated_wood_boiler_stove = ProductionSystem.objects.get(
        identifier="granulated_wood_boiler_stove"
    )

    granulated_wood_boiler_stove.investment_individual_hot_water = 5000
    granulated_wood_boiler_stove.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "energies",
            "0007_auto_20200820_1628_fix_solar_system_combined_maintenance_price",
        ),
    ]

    operations = [
        migrations.RunPython(
            fix_granulated_wood_boiler_maintenance_price,
            reverse_code=unfix_granulated_wood_boiler_maintenance_price,
        ),
    ]
