# Generated by Django 2.2 on 2019-04-30 12:38

from django.db import migrations, models
import django.utils.timezone
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0007_energyvector_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingHeatingConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('criterion', models.CharField(choices=[('before_1948', 'Avant 1948'), ('between_1948_1974', 'Entre 1948 et 1974'), ('between_1975_1982', 'Entre 1975 et 1982'), ('between_1983_1988', 'Entre 1983 et 1988'), ('between_1989_2000', 'Entre 1989 et 2000'), ('between_2001_2005', 'Entre 2001 et 2005'), ('between_2006_2012', 'Entre 2006 et 2012'), ('after_2012', 'Après 2012'), ('bbc', 'Bâtiment BBC'), ('passive', 'Bâtiment passif')], max_length=30, unique=True, verbose_name='Critère')),
                ('heating_consumption', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Consommation de chauffage en kWh/m²')),
                ('comment', models.CharField(blank=True, default='', max_length=50, verbose_name='Commentaire')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Consommation en chauffage',
            },
        ),
    ]
