# Generated by Django 2.2 on 2019-04-30 12:38

from django.db import migrations


def load_data(apps, schema_editor):
    BuildingHeatingConsumption = apps.get_model("energies", "BuildingHeatingConsumption")
    BuildingHeatingConsumption.objects.bulk_create([
        BuildingHeatingConsumption(criterion="before_1948", heating_consumption=220, comment="", order=10),
        BuildingHeatingConsumption(criterion="between_1948_1974", heating_consumption=300, comment="", order=20),
        BuildingHeatingConsumption(criterion="between_1975_1982", heating_consumption=220, comment="RT 74", order=30),
        BuildingHeatingConsumption(criterion="between_1983_1988", heating_consumption=160, comment="RT 82", order=40),
        BuildingHeatingConsumption(criterion="between_1989_2000", heating_consumption=120, comment="RT 88", order=50),
        BuildingHeatingConsumption(criterion="between_2001_2005", heating_consumption=100, comment="RT 2000", order=60),
        BuildingHeatingConsumption(criterion="between_2006_2012", heating_consumption=85, comment="RT 2005", order=70),
        BuildingHeatingConsumption(criterion="after_2012", heating_consumption=32, comment="RT 2012", order=80),
        BuildingHeatingConsumption(criterion="bbc", heating_consumption=60, comment="Label BBC", order=90),
        BuildingHeatingConsumption(criterion="passive", heating_consumption=15, comment="Label Passiv Haus", order=100),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0008_buildingheatingconsumption'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_code=migrations.RunPython.noop),
    ]
