# Generated by Django 2.2.10 on 2020-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0008_auto_20200820_1637_fix_granulated_wood_boiler_investment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryefficiency',
            name='is_hydro',
            field=models.BooleanField(default=True, verbose_name='With hydrolic system ?'),
        ),
    ]
