# Generated by Django 2.2.10 on 2020-08-20 15:05
from decimal import Decimal
from django.db import migrations


def load_data(apps, schema_editor):
    SecondaryEfficiency = apps.get_model("energies", "SecondaryEfficiency")
    SecondaryEfficiency.objects.create(
        is_heating=True, is_multi_unit=False, is_hydro=False, ratio=Decimal("1")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("energies", "0009_secondaryefficiency_is_hydro"),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_code=migrations.RunPython.noop),
    ]
