# Generated by Django 2.2.10 on 2020-08-20 15:31

from django.db import migrations


def fix_solar_water_heater_investment_price(apps, schema_editor):
    ProductionSystem = apps.get_model("energies", "ProductionSystem")

    solar_water_heater = ProductionSystem.objects.get(identifier="solar_water_heater")

    solar_water_heater.investment_small_multi_unit_hot_water = 1000
    solar_water_heater.investment_medium_multi_unit_hot_water = 1000
    solar_water_heater.investment_large_multi_unit_hot_water = 1000
    solar_water_heater.save()


def unfix_granulated_wood_boiler_investment_price(apps, schema_editor):
    ProductionSystem = apps.get_model("energies", "ProductionSystem")

    solar_water_heater = ProductionSystem.objects.get(identifier="solar_water_heater")

    solar_water_heater.investment_small_multi_unit_hot_water = 1300
    solar_water_heater.investment_medium_multi_unit_hot_water = 1300
    solar_water_heater.investment_large_multi_unit_hot_water = 1300
    solar_water_heater.save()


class Migration(migrations.Migration):

    dependencies = [
        ("energies", "0010_secondaryefficiency_is_hydro_data"),
    ]

    operations = [
        migrations.RunPython(
            fix_solar_water_heater_investment_price,
            reverse_code=unfix_granulated_wood_boiler_investment_price,
        ),
    ]
