# Generated by Django 2.2 on 2019-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0011_productionsystem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='combustible_category',
            field=models.CharField(choices=[('fossil', 'Fossile'), ('electricity', 'Électricité'), ('renewable', 'Renouvelable')], default='fossil', max_length=30, verbose_name='Catégorie de combustible'),
        ),
    ]
