# Generated by Django 2.2 on 2019-05-28 11:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0013_energy_add_combustible_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018)], verbose_name='Année')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Montant HT / tCO2')),
            ],
            options={
                'verbose_name': 'Taxe carbone',
            },
        ),
    ]
