# Generated by Django 2.2 on 2019-05-28 11:35

from decimal import Decimal
from django.db import migrations


def load_data(apps, schema_editor):
    CarbonTax = apps.get_model("energies", "CarbonTax")

    CarbonTax.objects.bulk_create([
        CarbonTax(year=2018, amount=Decimal('44.6')),
        CarbonTax(year=2019, amount=Decimal('50')),
        CarbonTax(year=2020, amount=Decimal('65.4')),
        CarbonTax(year=2021, amount=Decimal('75.8')),
        CarbonTax(year=2022, amount=Decimal('86.2')),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0014_carbontax'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_code=migrations.RunPython.noop),
    ]
