# Generated by Django 2.2 on 2019-05-28 10:03

from django.db import migrations


def update_data(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")

    data = [
        {'pk': 1, 'ghg_ratio': 0.300},
        {'pk': 2, 'ghg_ratio': 0.234},
        {'pk': 3, 'ghg_ratio': 0.234},
        {'pk': 4, 'ghg_ratio': 0.274},
        {'pk': 5, 'ghg_ratio': 0.18},
        {'pk': 6, 'ghg_ratio': 0.013},
        {'pk': 7, 'ghg_ratio': 0.013},
        {'pk': 8, 'ghg_ratio': 0.013},
        {'pk': 9, 'ghg_ratio': 0.013},
    ]

    for entry in data:
        energy = Energy.objects.get(pk=entry['pk'])
        energy.ghg_ratio = entry['ghg_ratio']
        energy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0015_carbontax_data'),
    ]

    operations = [
        migrations.RunPython(update_data, reverse_code=migrations.RunPython.noop),
    ]
