# Generated by Django 2.2 on 2019-06-07 12:11

import core.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0016_energy_update_ghg_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryEfficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_heating', models.BooleanField(default=False, verbose_name='Chauffage ?')),
                ('is_multi_unit', models.BooleanField(default=False, verbose_name='Collectif ?')),
                ('ratio', models.DecimalField(decimal_places=10, default=0, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ratio')),
            ],
            options={
                'verbose_name': 'Rendement secondaire',
            },
        ),
    ]
