# Generated by Django 2.2 on 2019-06-07 11:58

from decimal import Decimal
from django.db import migrations


def load_data(apps, schema_editor):
    SecondaryEfficiency = apps.get_model("energies", "SecondaryEfficiency")

    SecondaryEfficiency.objects.bulk_create([
        SecondaryEfficiency(is_heating=True, is_multi_unit=False, ratio=Decimal('0.85')),
        SecondaryEfficiency(is_heating=True, is_multi_unit=True, ratio=Decimal('0.85')),
        SecondaryEfficiency(is_heating=False, is_multi_unit=False, ratio=Decimal('0.874')),
        SecondaryEfficiency(is_heating=False, is_multi_unit=True, ratio=Decimal('0.5')),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0017_secondaryefficiency'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_code=migrations.RunPython.noop),
    ]
