# Generated by Django 2.2.3 on 2019-07-19 07:14

from decimal import Decimal

from django.db import migrations


def load_data(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")
    network = Energy.objects.get(identifier="network")

    # Ensure price exists
    energy_price_2019, created = network.yearly_energy_price.get_or_create(year=2019)
    energy_price_2019.price = Decimal("3.65")
    energy_price_2019.save()

    # Setup multi_unit discount
    network.price_multi_unit_discount = Decimal("0.96")
    network.save()


# def unload_data(apps, schema_editor):
#     Energy = apps.get_model("energies", "Energy")
#     network = Energy.objects.get(identifier="network")

#     network.yearly_energy_price.filter(year=2019).delete()


class Migration(migrations.Migration):

    dependencies = [("energies", "0021_energy_price_multi_unit_discount")]

    operations = [
        migrations.RunPython(load_data, reverse_code=migrations.RunPython.noop)
    ]

