# Generated by Django 2.2.3 on 2019-08-14 08:36

from decimal import Decimal
from django.db import migrations


def load_data(apps, schema_editor):
    ProductionSystem = apps.get_model("energies", "ProductionSystem")

    ProductionSystem.objects.filter(
        identifier__in=("recent_log_boiler_stove", "granulated_wood_boiler_stove")
    ).update(enr_ratio_hot_water=Decimal("1"))


class Migration(migrations.Migration):

    dependencies = [("energies", "0022_fix_network_price")]

    operations = [
        migrations.RunPython(load_data, reverse_code=migrations.RunPython.noop)
    ]

