# Generated by Django 2.2.3 on 2019-08-19 12:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


def fix_pci(apps, schema_editor):
    EnergyVector = apps.get_model("energies", "EnergyVector")
    EnergyVector.objects.filter(vector='oil_l').update(pci=Decimal('10.384'))


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0023_fix_enr_ratio_productionsystem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyvector',
            name='pci',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pouvoir calorifique inférieur en kWh/unité'),
        ),
        migrations.RunPython(fix_pci, reverse_code=migrations.RunPython.noop)
    ]
