# Generated by Django 2.2.3 on 2019-08-22 08:04

from django.db import migrations
from decimal import Decimal


def fix_secondary_efficiency(apps, schema_editor):
    SecondaryEfficiency = apps.get_model("energies", "SecondaryEfficiency")
    SecondaryEfficiency.objects.filter(is_heating=False, is_multi_unit=False).update(
        ratio=Decimal("0.87")
    )


class Migration(migrations.Migration):

    dependencies = [("energies", "0025_fix_propane_energy_vector")]

    operations = [
        migrations.RunPython(
            fix_secondary_efficiency, reverse_code=migrations.RunPython.noop
        )
    ]

