# Generated by Django 2.2.3 on 2019-08-23 07:45

from django.db import migrations
from decimal import Decimal


def update_energy_prices(apps, schema_editor):
    YearlyEnergyPrice = apps.get_model("energies", "YearlyEnergyPrice")

    energy_prices_2019 = {
        "oil": Decimal("7.65"),
        "propane": Decimal("13.13"),
        "gaz_b1": Decimal("6.79"),
        "electricity": Decimal("15.92"),
        "bulk_granules": Decimal("5.74"),
        "bag_granules": Decimal("6.00"),
        "wood": Decimal("4.20"),
        "shredded_wood": Decimal("3.52"),
        "network": Decimal("3.65"),
    }

    for energy_identifier, energy_price in energy_prices_2019.items():
        YearlyEnergyPrice.objects.filter(
            energy__identifier=energy_identifier, year=2019
        ).update(price=energy_price)


def update_shredded_wood_multi_unit_disount(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")
    Energy.objects.filter(identifier="shredded_wood").update(
        price_multi_unit_discount=Decimal("0.87")
    )


class Migration(migrations.Migration):

    dependencies = [("energies", "0026_fix_secondary_efficiency_ind_hotwater")]

    operations = [
        migrations.RunPython(
            update_energy_prices, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            update_shredded_wood_multi_unit_disount,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
