# Generated by Django 2.2.3 on 2019-08-23 07:54

from django.db import migrations
from decimal import Decimal


def update_energy_price_variations(apps, schema_editor):
    Energy = apps.get_model("energies", "Energy")

    energy_price_variations = {
        "oil": Decimal("3.46"),
        "propane": Decimal("2.95"),
        "gaz_b1": Decimal("1.32"),
        "electricity": Decimal("2.80"),
        "bulk_granules": Decimal("3.12"),
        "bag_granules": Decimal("3.12"),
        "wood": Decimal("2.73"),
        "shredded_wood": Decimal("2.06"),
        "network": Decimal("2.00"),
    }

    for identifier, price_variation in energy_price_variations.items():
        Energy.objects.filter(
            identifier=identifier
        ).update(price_variation=price_variation)


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0027_update_energy_prices_2019'),
    ]

    operations = [
        migrations.RunPython(
            update_energy_price_variations, reverse_code=migrations.RunPython.noop
        ),
    ]
