# Generated by Django 2.1.5 on 2019-01-11 10:02

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("postcode", models.CharField(blank=True, max_length=8)),
                ("inseecode", models.CharField(max_length=8, unique=True)),
                ("geom", djgeojson.fields.PointField()),
            ],
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("inseecode", models.CharField(max_length=8, unique=True)),
                ("geom", djgeojson.fields.PointField()),
            ],
        ),
        migrations.CreateModel(
            name="Epci",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("inseecode", models.CharField(max_length=9, unique=True)),
                ("geom", djgeojson.fields.PointField()),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("inseecode", models.CharField(max_length=8, unique=True)),
                ("geom", djgeojson.fields.PointField()),
            ],
        ),
        migrations.AddField(
            model_name="departement",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="territories.Region"
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="departement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="territories.Departement",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="epci",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="territories.Epci",
            ),
        ),
    ]
