# Generated by Django 2.1.5 on 2019-03-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='epci',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
    ]
