# Generated by Django 2.2.3 on 2019-11-06 17:47

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0002_auto_20190308_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='commune',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='departement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='departement',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='epci',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='epci',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='region',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
