# Generated by Django 2.2.10 on 2020-03-25 17:36

import actimmo_map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actimmo_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actimmocontact',
            name='group_name_overide',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='overide group name'),
        ),
        migrations.AddField(
            model_name='actimmocontact',
            name='group_profile_pic_overide',
            field=models.ImageField(blank=True, null=True, upload_to=actimmo_map.models.group_directory_path),
        ),
        migrations.AddField(
            model_name='actimmocontact',
            name='group_website_overide',
            field=models.URLField(blank=True, null=True, verbose_name='overide web site url'),
        ),
        migrations.AlterField(
            model_name='actimmocontact',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction'),
        ),
    ]
