# Generated by Django 2.2.11 on 2020-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actimmo_map', '0002_auto_20200325_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='actimmocontact',
            name='group_full_name_overide',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='overide group full name'),
        ),
    ]
