# Generated by Django 2.1.5 on 2019-03-18 14:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_auto_20190308_2318'),
        ('territories', '0002_auto_20190308_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchmentArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('additionnal_information', models.TextField(blank=True, null=True, verbose_name="Information complémentaire pour les CIE lors de l'accueil téléphonique")),
                ('group', models.ForeignKey(blank=True, help_text='Groupe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catchment_area', to='accounts.Group', verbose_name='Groupe')),
                ('territories', models.ManyToManyField(to='territories.Commune', verbose_name='Territoires')),
            ],
            options={
                'verbose_name': 'Zone de chalandise',
                'verbose_name_plural': 'Zones de chalandise',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('presentation', models.TextField(blank=True, null=True, verbose_name='Présentation du lieu')),
                ('internal_presentation', models.TextField(blank=True, null=True, verbose_name='Présentation du lieu à destination des conseillers')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, verbose_name='Numéro de téléphone')),
                ('is_active', models.BooleanField(default=True, help_text='Lieu actif ?', verbose_name='active')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('postcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='Code postal')),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Londitude')),
                ('inseecode', models.CharField(blank=True, max_length=8, null=True, verbose_name='Code INSEE')),
                ('url', models.URLField(verbose_name='Url')),
                ('groups', models.ManyToManyField(to='accounts.Group', verbose_name='Structures attachées à ce lieux')),
            ],
            options={
                'verbose_name': 'Lieu de conseil',
                'verbose_name_plural': 'Lieux de conseil',
                'ordering': ('name',),
            },
        ),
    ]
