# Generated by Django 2.1.7 on 2019-03-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0002_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Lieu actif ?', verbose_name='active'),
        ),
    ]
