# Generated by Django 2.1.7 on 2019-03-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0003_slot_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('start_date',), 'verbose_name': 'Créneau'},
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='name',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='time_start',
        ),
        migrations.AddField(
            model_name='place',
            name='color',
            field=models.CharField(default='#888888', max_length=10, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='slot',
            name='end_date',
            field=models.DateTimeField(default=None, verbose_name='Date et heure de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dialogwatt.Place', verbose_name='Lieu de conseil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='start_date',
            field=models.DateTimeField(default=None, verbose_name='Date et heure de début'),
            preserve_default=False,
        ),
    ]
