# Generated by Django 2.1.7 on 2019-03-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190308_2318'),
        ('dialogwatt', '0004_auto_20190324_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('duration', models.IntegerField(default=0, verbose_name='Durée (en minutes)')),
                ('internal_description', models.TextField(blank=True, null=True, verbose_name='Présentation interne service')),
                ('show_description', models.BooleanField(default=True, verbose_name='Montrer la description du service')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Présentation du service')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'Motifs de rendez-vous',
                'ordering': ('name',),
            },
        ),
    ]
