# Generated by Django 2.1.7 on 2019-03-29 18:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0005_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='form',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
