# Generated by Django 2.1.7 on 2019-03-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0006_reason_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='reasons',
            field=models.ManyToManyField(to='dialogwatt.Reason', verbose_name='Motifs de rendez-vous'),
        ),
    ]
