# Generated by Django 2.2 on 2019-04-09 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20190308_2318'),
        ('dialogwatt', '0007_slot_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la notification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('trigger', models.CharField(choices=[('created_client', 'Création par le contact'), ('changed_client', 'Modification par le contact'), ('canceled_client', 'Annulation par le contact'), ('created_advisor', 'Création pour le conseiller'), ('changed_advisor', 'Modification par le conseiller'), ('canceled_advisor', 'Annulation par le conseiller')], max_length=100, verbose_name='Déclencheur')),
                ('term', models.CharField(choices=[('immediate', 'Instantané'), ('delayed', 'Différé')], default='immediate', max_length=10, verbose_name='Délai')),
                ('term_days', models.PositiveIntegerField(default=0, verbose_name='Délai en jours')),
                ('term_day_type', models.CharField(choices=[('calendar', 'Calendaire'), ('open', 'Ouvrés (hors WE)')], default='calendar', max_length=10, verbose_name='Type de jours de délai')),
                ('term_after_before', models.CharField(choices=[('after', 'Après'), ('before', 'Avant')], default='before', max_length=10, verbose_name='Avant ou après')),
                ('term_time', models.TimeField(verbose_name="Heure d'envoi")),
                ('to', models.CharField(choices=[('contact', 'Contact'), ('all_advisors', 'Tous les conseillers'), ('some_advisors', 'Des conseillers'), ('allocated_advisor', 'Le conseiller concerné par le rdv')], max_length=100, verbose_name='Destinataire')),
                ('sms_is_active', models.BooleanField(default=True, verbose_name='Sms actif ?')),
                ('sms_message', models.TextField(blank=True, null=True, verbose_name='Texte SMS')),
                ('mail_is_active', models.BooleanField(default=True, verbose_name='Mail actif ?')),
                ('mail_message', models.TextField(blank=True, null=True, verbose_name='Texte MAIL')),
                ('chat_is_active', models.BooleanField(default=True, verbose_name='Chat actif ?')),
                ('chat_message', models.TextField(blank=True, null=True, verbose_name='Texte CHAT')),
                ('advisors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Conseillers')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group', verbose_name='Structure')),
                ('place', models.ManyToManyField(to='dialogwatt.Place', verbose_name='Lieu de conseil')),
                ('reasons', models.ManyToManyField(to='dialogwatt.Reason', verbose_name='Motifs de rendez-vous')),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ('name',),
            },
        ),
    ]
