# Generated by Django 2.2 on 2019-04-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='place',
            new_name='places',
        ),
    ]
