# Generated by Django 2.2 on 2019-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0009_auto_20190409_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='places',
            field=models.ManyToManyField(to='dialogwatt.Place', verbose_name='Lieux de conseil'),
        ),
    ]
