# Generated by Django 2.2 on 2019-04-09 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0010_auto_20190409_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='term_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name="Heure d'envoi"),
        ),
    ]
