# Generated by Django 2.2 on 2019-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0012_auto_20190410_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='public_description',
            field=models.TextField(blank=True, null=True, verbose_name='Présentation publique du créneau'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Présentation interne du créneau'),
        ),
    ]
