# Generated by Django 2.2 on 2019-04-30 11:56

from django.db import migrations, models
import django.utils.timezone
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0013_auto_20190410_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchmentarea',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='catchmentarea',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='reason',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='reason',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='updated_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
