# Generated by Django 2.2 on 2019-05-13 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialogwatt', '0015_exchange_exchangeattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('start_date', models.DateTimeField(verbose_name='Date et heure de début')),
                ('end_date', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('has_been_honored', models.BooleanField(default=False, verbose_name='Rendez-vous honoré ?')),
                ('advisor', models.ForeignKey(limit_choices_to={'user_type': 'advisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apointments_as_advisor', to=settings.AUTH_USER_MODEL, verbose_name='Conseiller')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apointments_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Contact')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialogwatt.Reason', verbose_name='Motif')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialogwatt.Slot', verbose_name='Créneau')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'ordering': ('start_date',),
            },
        ),
    ]
