# Generated by Django 2.2 on 2019-05-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0016_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialogwatt.Place', verbose_name='Lieu'),
        ),
    ]
