# Generated by Django 2.2.2 on 2019-06-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0019_auto_20190609_2221'),
        ('dialogwatt', '0019_auto_20190604_1429'),
    ]

    operations = [
    ]
