# Generated by Django 2.2.2 on 2019-07-01 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialogwatt', '0021_place_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='selected_advisors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Conseillers intervenant sur ce lieu'),
        ),
        migrations.AlterField(
            model_name='place',
            name='groups',
            field=models.ManyToManyField(to='accounts.Group', verbose_name='Structures attachées à ce lieu'),
        ),
    ]
