# Generated by Django 2.2.3 on 2019-07-04 07:34

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Appointment = apps.get_model('dialogwatt', 'Appointment')
    for appointment in Appointment.objects.all():
        appointment.uuid = uuid.uuid4()
        appointment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0023_calendarpermanenturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(unique=True)
        )
    ]
