# Generated by Django 2.2.3 on 2019-07-04 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0024_appointment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'En attente de validation'), ('validated', 'Validé'), ('canceled', 'Annulé')], default='validated', max_length=100, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
