# Generated by Django 2.2.3 on 2019-10-03 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('dialogwatt', '0025_auto_20190704_1026'), ('dialogwatt', '0026_appointment_sequence'), ('dialogwatt', '0027_reason_color'), ('dialogwatt', '0028_calendarpermanenturl_reasons'), ('dialogwatt', '0029_auto_20190713_2304')]

    dependencies = [
        ('dialogwatt', '0024_appointment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'En attente de validation'), ('validated', 'Validé'), ('canceled', 'Annulé')], default='validated', max_length=100, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sequence',
            field=models.IntegerField(default=-1, verbose_name="Séquence : numéro d'update"),
        ),
        migrations.AddField(
            model_name='reason',
            name='color',
            field=models.CharField(default='#888888', max_length=10, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='calendarpermanenturl',
            name='reasons',
            field=models.ManyToManyField(to='dialogwatt.Reason', verbose_name='Motifs de rdv'),
        ),
        migrations.AddField(
            model_name='slot',
            name='sequence',
            field=models.IntegerField(default=-1, verbose_name="Séquence : numéro d'update"),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('validated', 'Validé'), ('canceled', 'Annulé')], default='validated', max_length=100, verbose_name='Statut'),
        ),
    ]
