# Generated by Django 2.2.3 on 2019-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0025_auto_20190704_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sequence',
            field=models.IntegerField(default=-1, verbose_name="Séquence : numéro d'update"),
        ),
    ]
