# Generated by Django 2.2.3 on 2019-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0026_appointment_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='color',
            field=models.CharField(default='#888888', max_length=10, verbose_name='Color'),
        ),
    ]
