# Generated by Django 2.2.3 on 2019-07-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0027_reason_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarpermanenturl',
            name='reasons',
            field=models.ManyToManyField(to='dialogwatt.Reason', verbose_name='Motifs de rdv'),
        ),
    ]
