# Generated by Django 2.2.3 on 2019-07-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0028_calendarpermanenturl_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='sequence',
            field=models.IntegerField(default=-1, verbose_name="Séquence : numéro d'update"),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('validated', 'Validé'), ('canceled', 'Annulé')], default='validated', max_length=100, verbose_name='Statut'),
        ),
    ]
