# Generated by Django 2.2.3 on 2019-07-13 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0030_slot_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
