# Generated by Django 2.2.3 on 2019-10-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0031_auto_20190713_2308_squashed_0035_exchange_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_date',
            field=models.DateTimeField(verbose_name='Date et heure de fin'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogwatt.Place', verbose_name='Lieu de conseil'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_date',
            field=models.DateTimeField(verbose_name='Date et heure de début'),
        ),
    ]
