# Generated by Django 2.2.3 on 2019-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0031_auto_20190713_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('created_account', "Création d'un compte par le contact"), ('created_client', "Création d'un rdv par le contact"), ('changed_client', "Modification d'un rdv par le contact"), ('canceled_client', "Annulation d'un rdv par le contact"), ('created_advisor', "Création d'un rdv par le conseiller"), ('changed_advisor', "Modification d'un rdv par le conseiller"), ('canceled_advisor', "Annulation d'un rdv par le conseiller"), ('date_of_appointment', 'Échéance du rendez-vous')], max_length=100, verbose_name='Déclencheur'),
        ),
    ]
