# Generated by Django 2.2.3 on 2019-09-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0032_auto_20190714_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification'},
        ),
    ]
