# Generated by Django 2.2.9 on 2020-01-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0033_auto_20191217_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchmentarea',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
