# Generated by Django 2.2.9 on 2020-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0033_auto_20191217_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tmp_book_date',
            field=models.DateTimeField(null=True, verbose_name='Date et heure de réservation temporaire'),
        ),
    ]
