# Generated by Django 2.2.10 on 2020-02-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0034_auto_20200113_1733'),
        ('dialogwatt', '0034_appointment_tmp_book_date'),
    ]

    operations = [
    ]
