# Generated by Django 2.2.3 on 2019-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0034_auto_20190920_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='trigger',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Déclencheur'),
        ),
    ]
