# Generated by Django 2.2.10 on 2020-09-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0038_appointment_form_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'En attente de validation'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='validated', max_length=100, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('created_account', "Création d'un compte par le contact"), ('created_client', "Création d'un rdv par le contact"), ('changed_client', "Modification d'un rdv par le contact"), ('cancelled_client', "Annulation d'un rdv par le contact"), ('created_advisor', "Création d'un rdv par le conseiller"), ('changed_advisor', "Modification d'un rdv par le conseiller"), ('cancelled_advisor', "Annulation d'un rdv par le conseiller"), ('date_of_appointment', 'Échéance du rendez-vous')], max_length=100, verbose_name='Déclencheur'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('validated', 'Validé'), ('cancelled', 'Annulé')], default='validated', max_length=100, verbose_name='Statut'),
        ),
    ]
