# Generated by Django 2.2.10 on 2020-09-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dialogwatt', '0040_auto_20200910_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='to_account',
        ),
        migrations.AddField(
            model_name='exchange',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
