# Generated by Django 2.2.10 on 2020-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0041_auto_20200910_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name="Message d'erreur"),
        ),
    ]
