# Generated by Django 2.2.10 on 2020-09-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0080_auto_20200724_1528'),
        ('dialogwatt', '0042_auto_20200912_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacContactForDialogwatt',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fac.contact',),
        ),
    ]
