# Generated by Django 2.2.10 on 2020-09-14 13:15

from django.db import migrations


def update_notification_trigger(apps, schema_editor):
    Notification = apps.get_model('dialogwatt', 'Notification')
    Notification.objects.filter(trigger='canceled_client').update(trigger="cancelled_client")
    Notification.objects.filter(trigger='canceled_advisor').update(trigger="cancelled_advisor")

    
def downgrade_notification_trigger(apps, schema_editor):
    Notification = apps.get_model('dialogwatt', 'Notification')
    Notification.objects.filter(trigger='cancelled_client').update(trigger="canceled_client")
    Notification.objects.filter(trigger='cancelled_advisor').update(trigger="canceled_advisor")


class Migration(migrations.Migration):
    """
    Change notification.trigger to reflect type correction done in 0039_auto_20200910_0958.py
    """
    dependencies = [
        ('dialogwatt', '0043_faccontactfordialogwatt'),
    ]

    operations = [
        migrations.RunPython(update_notification_trigger, downgrade_notification_trigger),
    ]
