# Generated by Django 2.2.10 on 2020-09-15 09:09

from django.db import migrations, models


def update(apps, schema_editor):
    Slot = apps.get_model('dialogwatt', 'Slot')
    Slot.objects.filter(is_active=False).update(status="inactive")

    
def downgrade(apps, schema_editor):
    Slot = apps.get_model('dialogwatt', 'Slot')
    Slot.objects.filter(status="validated").update(is_active=True)
    Slot.objects.filter(status="inactive").update(is_active=False)
    Slot.objects.filter(status="canceled").update(is_active=False)

    
class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0044_auto_20200914_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('validated', 'Validé'), ('inactive', 'Désactivé'), ('cancelled', 'Annulé')], default='validated', max_length=100, verbose_name='Statut'),
        ),
        migrations.RunPython(update, downgrade),
        migrations.RemoveField(
            model_name='slot',
            name='is_active',
        ),
    ]
