# Generated by Django 2.2.10 on 2020-10-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_group_address'),
        ('dialogwatt', '0045_auto_20200915_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Group', verbose_name='Structure'),
        ),
    ]
