# Generated by Django 2.2.10 on 2020-10-07 16:10

from django.db import migrations, models
import django.db.models.deletion


def update_group(apps, schema_editor):
    Exchange = apps.get_model('dialogwatt', 'Exchange')
    for exchange in Exchange.objects.all():
        if exchange.from_account is not None and exchange.from_account.group is not None:
            exchange.group = exchange.from_account.group
            exchange.save()
            continue

        to_account = apps.get_model('accounts', 'User').objects.get(pk=exchange.object_id)
        if getattr(to_account, 'group', None) is not None:
            exchange.group = to_account.group
            exchange.save()
            continue

    Exchange.objects.filter(group=None).delete()
    return

    
def downgrade_group(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0046_exchange_group'),
    ]

    operations = [
        migrations.RunPython(update_group, downgrade_group, atomic=True),
    ]
