# Generated by Django 2.2.10 on 2020-10-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0048_exchange_group_alter_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Présentation interne du créneau'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='public_description',
            field=models.TextField(blank=True, default='', verbose_name='Présentation publique du créneau'),
            preserve_default=False,
        ),
    ]
