# Generated by Django 2.2.17 on 2021-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogwatt', '0053_auto_20201125_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchmentarea',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Zone de chalandise active ?', verbose_name='active'),
        ),
    ]
