# Generated by Django 2.2.10 on 2020-11-11 23:15

import core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_group_address'),
        ('fac', '0083_auto_20201027_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('anchor', models.CharField(max_length=100, verbose_name='Ancre')),
                ('version', models.IntegerField(default=0, verbose_name='Version')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('form', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Formulaire')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Group', verbose_name='Structure')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fac.Project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Formulaire personnalisé',
                'verbose_name_plural': 'Formulaires personnalisés',
                'unique_together': {('model', 'anchor', 'version')},
            },
        ),
    ]
