# Generated by Django 2.2.10 on 2020-11-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0083_auto_20201027_1517'),
        ('custom_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='folder_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fac.FolderModel', verbose_name='Modèle de dossier'),
        ),
    ]
