# Generated by Django 2.2.10 on 2020-11-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0003_auto_20201117_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='folder_models',
            field=models.ManyToManyField(blank=True, related_name='custom_forms', to='fac.FolderModel', verbose_name='Modèle de dossiers'),
        ),
        migrations.AlterField(
            model_name='customform',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_forms', to='accounts.Group', verbose_name='Groupes'),
        ),
        migrations.AlterField(
            model_name='customform',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='custom_forms', to='fac.Project', verbose_name='Projets'),
        ),
    ]
