# Generated by Django 2.2.10 on 2020-11-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0005_customform_action_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customform',
            unique_together=set(),
        ),
    ]
