# Generated by Django 2.2.10 on 2020-11-20 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0006_auto_20201120_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='form',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Use https://jsonformatter.curiousconcept.com/ to validate', verbose_name='Formulaire'),
        ),
    ]
