# Generated by Django 2.2.3 on 2019-09-17 14:37

import core.models
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone
import helpers.mixins.universal_repr_mixin
import uuid


class Migration(migrations.Migration):

    replaces = [('pdf_generator', '0001_initial'), ('pdf_generator', '0002_auto_20190410_1546'), ('pdf_generator', '0003_auto_20190414_1941'), ('pdf_generator', '0004_auto_20190430_1356')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTempStore',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'verbose_name': 'Pdf Temporary Store',
            },
            bases=(helpers.mixins.universal_repr_mixin.UniversalReprMixin, models.Model),
        ),
    ]
