# Generated by Django 2.2.10 on 2020-06-02 11:48

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0001_initial_squashed_0004_auto_20190430_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftempstore',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
