# Generated by Django 2.1.8 on 2019-04-10 13:46

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations
import django.utils.timezone
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftempstore',
            name='created_at',
            field=core.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pdftempstore',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
