# Generated by Django 2.1.8 on 2019-04-14 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0002_auto_20190410_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftempstore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
