# Generated by Django 2.2 on 2019-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0003_auto_20190414_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdftempstore',
            options={'verbose_name': 'Pdf Temporary Store'},
        ),
    ]
